package View;

import DAO.DAO_Login;
import Model.Model_Login;
import Service.Service_Login;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Form_Login extends javax.swing.JFrame {

    private Service_Login servis = new DAO_Login();
    public static boolean tutup = false;
    /**
    * Creates new form AplikasiLogin
    */
    public Form_Login() {
        initComponents();
        
        this.setBackground(new Color(0,0,0,0));
        bt_login.requestFocus();
    }
    
    void bersih(){
        t_username.setText("username");
        t_password.setText("password");
        //t_level.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_user = new javax.swing.JPanel();
        icon_user = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        bt_keluar = new javax.swing.JLabel();
        pn_pass = new javax.swing.JPanel();
        icon_pass = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        bt_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TokoBesiGriyaWarna = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_user.setBackground(new java.awt.Color(255, 255, 255));
        pn_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        icon_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Staff_20px_2.png"))); // NOI18N

        t_username.setBackground(new java.awt.Color(255, 255, 255));
        t_username.setFont(new java.awt.Font("Square721 BT", 0, 20)); // NOI18N
        t_username.setForeground(new java.awt.Color(23, 48, 148));
        t_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_username.setText("username");
        t_username.setBorder(null);
        t_username.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        t_username.setSelectionColor(new java.awt.Color(51, 51, 51));
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_userLayout = new javax.swing.GroupLayout(pn_user);
        pn_user.setLayout(pn_userLayout);
        pn_userLayout.setHorizontalGroup(
            pn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_user)
                .addGap(18, 18, 18)
                .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pn_userLayout.setVerticalGroup(
            pn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_user)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(t_username)
        );

        jPanel1.add(pn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        bt_keluar.setBackground(new java.awt.Color(53, 39, 133));
        bt_keluar.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        bt_keluar.setForeground(new java.awt.Color(255, 255, 255));
        bt_keluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_keluar.setText("X");
        bt_keluar.setOpaque(true);
        bt_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_keluarMouseClicked(evt);
            }
        });
        jPanel1.add(bt_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 30, 30));

        pn_pass.setBackground(new java.awt.Color(255, 255, 255));
        pn_pass.setForeground(new java.awt.Color(0, 0, 0));
        pn_pass.setPreferredSize(new java.awt.Dimension(262, 46));

        icon_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Password_20px_3.png"))); // NOI18N

        t_password.setBackground(new java.awt.Color(255, 255, 255));
        t_password.setForeground(new java.awt.Color(23, 48, 148));
        t_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_password.setText("password");
        t_password.setBorder(null);
        t_password.setCaretColor(new java.awt.Color(153, 153, 153));
        t_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passwordFocusLost(evt);
            }
        });
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });
        t_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_passwordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pn_passLayout = new javax.swing.GroupLayout(pn_pass);
        pn_pass.setLayout(pn_passLayout);
        pn_passLayout.setHorizontalGroup(
            pn_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_passLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pn_passLayout.setVerticalGroup(
            pn_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_passLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_pass)
                .addGap(22, 22, 22))
            .addGroup(pn_passLayout.createSequentialGroup()
                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(pn_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        bt_login.setBackground(new java.awt.Color(23, 48, 148));
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_loginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_loginMousePressed(evt);
            }
        });
        bt_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_loginKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout bt_loginLayout = new javax.swing.GroupLayout(bt_login);
        bt_login.setLayout(bt_loginLayout);
        bt_loginLayout.setHorizontalGroup(
            bt_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_loginLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        bt_loginLayout.setVerticalGroup(
            bt_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 260, -1));

        TokoBesiGriyaWarna.setBackground(new java.awt.Color(0, 51, 204));
        TokoBesiGriyaWarna.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        TokoBesiGriyaWarna.setForeground(new java.awt.Color(255, 255, 255));
        TokoBesiGriyaWarna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TokoBesiGriyaWarna.setText("MUSIC STORE ");
        TokoBesiGriyaWarna.setAutoscrolls(true);
        TokoBesiGriyaWarna.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(TokoBesiGriyaWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundLogin66.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
    }//GEN-LAST:event_formWindowActivated

    private void t_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passwordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            bt_login.requestFocus();
        }
    }//GEN-LAST:event_t_passwordKeyPressed

    private void t_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusLost
        String pass=t_password.getText();
        if(pass.equals("")||pass.equals("password")){
            t_password.setText("password");

        }
    }//GEN-LAST:event_t_passwordFocusLost

    private void t_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passwordFocusGained
        String pass=t_password.getText();
        if(pass.equals("password")){
            t_password.setText("");

        }
    }//GEN-LAST:event_t_passwordFocusGained

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed

    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String user=t_username.getText();
        if(user.equals("")||user.equals("username")){
            t_username.setText("username");

        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String pass=t_username.getText();
        if(pass.equals("username")){
            t_username.setText("");

        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void bt_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_keluarMouseClicked
        dispose();
    }//GEN-LAST:event_bt_keluarMouseClicked

    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        prosesLogin();
    }//GEN-LAST:event_bt_loginMouseClicked

    private void bt_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseEntered
        bt_login.setBackground(new Color(45,33,114));
        
    }//GEN-LAST:event_bt_loginMouseEntered

    private void bt_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseExited
        bt_login.setBackground(new Color(53,39,133));
        
    }//GEN-LAST:event_bt_loginMouseExited

    private void bt_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMousePressed
        bt_login.setBackground(new Color(30,20,86));
        
    }//GEN-LAST:event_bt_loginMousePressed

    private void bt_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_loginKeyPressed
        prosesLogin();
    }//GEN-LAST:event_bt_loginKeyPressed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TokoBesiGriyaWarna;
    private javax.swing.JLabel bt_keluar;
    private javax.swing.JPanel bt_login;
    private javax.swing.JLabel icon_pass;
    private javax.swing.JLabel icon_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pn_pass;
    private javax.swing.JPanel pn_user;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables

    private void prosesLogin() {
        if(validasiInput()==true){
            String id       = t_username.getText();
            String user     = t_username.getText();
            String pass     = t_password.getText();

            Model_Login log = new Model_Login();

            log.setId_user(id);
            log.setUsername(user);
            log.setPass_user(pass);

            servis.prosesLogin(log);
            if(tutup){
                dispose();
            }
        }
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if (t_username.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        }else if (t_password.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        }else{
            valid = true;
        }
        return valid;
    }
}
