/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.Koneksi;
import DAO.DAO_Barang;
import DAO.DAO_DetBarangMasuk;
import DAO.DAO_Laporan;
import DAO.DAO_BarangMasuk;
import DAO.DAO_SemBarangMasuk;
import Model.Model_Barang;
import Model.Model_DetBarangMasuk;
import Model.Model_Distributor;
import Model.Model_JenisBarang;
import Model.Model_BarangMasuk;
import Model.Model_Pengguna;
import Model.Model_SemBarangMasuk;
import Service.Service_Barang;
import Service.Service_DetBarangMasuk;
import Service.Service_Laporan;
import Service.Service_BarangMasuk;
import Service.Service_SemBarangMasuk;
import TableModel.TblMod_Barang;
import TableModel.TblMod_DetBarangMasuk;
import TableModel.TblMod_BarangMasuk;
import TableModel.TblMod_SemBarangMasuk;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kelompok 4
 */
public class Form_BarangMasuk extends javax.swing.JPanel {
    
    private Connection conn;

    private Service_BarangMasuk servis_masuk = new DAO_BarangMasuk();
    private Service_DetBarangMasuk servis_detmasuk = new DAO_DetBarangMasuk();
    
    private TblMod_BarangMasuk tblModel_masuk = new TblMod_BarangMasuk();
    private TblMod_DetBarangMasuk tblModel_detmasuk = new TblMod_DetBarangMasuk();
    
    private Service_SemBarangMasuk servis = new DAO_SemBarangMasuk();
    private TblMod_SemBarangMasuk tblModel = new TblMod_SemBarangMasuk();
    
    private Service_Laporan servis_lap = new DAO_Laporan();
    
    public Form_BarangMasuk(String Id) {
        initComponents();
        
        conn = Koneksi.getConnection();
        
        //Pengaturan Tabel BarangMasuk
        tbl_BarangMasuk.setModel(tblModel_masuk);
        
        tbl_BarangMasuk.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_BarangMasuk.getTableHeader().setOpaque(false);
        tbl_BarangMasuk.getTableHeader().setBackground(new Color(0,48,88));
        tbl_BarangMasuk.getTableHeader().setForeground(new Color(255,255,255));
        tbl_BarangMasuk.setRowHeight(27);
        
        //Pengaturan Tabel Sementara
        tbl_sementara.setModel(tblModel);
        tbl_sementara.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_sementara.getTableHeader().setOpaque(false);
        tbl_sementara.getTableHeader().setBackground(new Color(0,48,88));
        tbl_sementara.getTableHeader().setForeground(new Color(255,255,255));
        tbl_sementara.setRowHeight(27);
        
        //Pengaturan Tabel Detail BarangMasuk Barang
        tbl_detail.setModel(tblModel);
        tbl_detail.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_detail.getTableHeader().setOpaque(false);
        tbl_detail.getTableHeader().setBackground(new Color(0,48,88));
        tbl_detail.getTableHeader().setForeground(new Color(255,255,255));
        tbl_detail.setRowHeight(27);
        
        lb_id.setText(Id);
        //setLocationRelativeTo(null);
        tbl_sementara.setModel(tblModel);
        tbl_BarangMasuk.setModel(tblModel_masuk);
        tbl_detail.setModel(tblModel_detmasuk);
        loadData();
        loadDataSementara();
        pn_detail.setVisible(false);
        resetForm();
        nonAktif();
    }
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarangMasuk = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BarangMasuk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bt_tambahdata = new javax.swing.JPanel();
        bt_data = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_detail = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bt_tambahdata5 = new javax.swing.JPanel();
        bt_data4 = new javax.swing.JLabel();
        tambahBarangMasuk = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        t_no = new javax.swing.JTextField();
        t_tanggal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sementara = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_iddis = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t_namadis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        t_kodbar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_nambar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t_harbar = new javax.swing.JTextField();
        t_jumbar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t_subtotal = new javax.swing.JTextField();
        t_satuan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bt_tambahdata1 = new javax.swing.JPanel();
        bt_tambah = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bt_hapusdata2 = new javax.swing.JPanel();
        bt_batal = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lb_tobar = new javax.swing.JLabel();
        bt_perbaruisem = new javax.swing.JPanel();
        bt_batal1 = new javax.swing.JLabel();
        bt_hapusem = new javax.swing.JPanel();
        bt_batal3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarangMasuk.setBackground(new java.awt.Color(255, 255, 255));
        dataBarangMasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));
        dataBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataBarangMasukMouseClicked(evt);
            }
        });

        tbl_BarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_BarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BarangMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_BarangMasuk);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Barang Masuk");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        bt_tambahdata.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdataMousePressed(evt);
            }
        });
        bt_tambahdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdataKeyPressed(evt);
            }
        });

        bt_data.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data.setForeground(new java.awt.Color(255, 255, 255));
        bt_data.setText("TAMBAH");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdataLayout = new javax.swing.GroupLayout(bt_tambahdata);
        bt_tambahdata.setLayout(bt_tambahdataLayout);
        bt_tambahdataLayout.setHorizontalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_data)
                .addGap(30, 30, 30))
        );
        bt_tambahdataLayout.setVerticalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon_Cari2.png"))); // NOI18N

        lb_id.setForeground(new java.awt.Color(255, 255, 255));
        lb_id.setText("lb_id");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 48, 88));
        jLabel4.setText("Detail Barang Masuk");

        jSeparator3.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_detail);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jSeparator3)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_tambahdata5.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata5MousePressed(evt);
            }
        });
        bt_tambahdata5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata5KeyPressed(evt);
            }
        });

        bt_data4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data4.setForeground(new java.awt.Color(255, 255, 255));
        bt_data4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_data4.setText("CETAK");

        javax.swing.GroupLayout bt_tambahdata5Layout = new javax.swing.GroupLayout(bt_tambahdata5);
        bt_tambahdata5.setLayout(bt_tambahdata5Layout);
        bt_tambahdata5Layout.setHorizontalGroup(
            bt_tambahdata5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_data4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_tambahdata5Layout.setVerticalGroup(
            bt_tambahdata5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_data4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataBarangMasukLayout = new javax.swing.GroupLayout(dataBarangMasuk);
        dataBarangMasuk.setLayout(dataBarangMasukLayout);
        dataBarangMasukLayout.setHorizontalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn_detail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataBarangMasukLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_tambahdata5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                        .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dataBarangMasukLayout.setVerticalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari)
                        .addComponent(bt_tambahdata5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(dataBarangMasuk, "card2");

        tambahBarangMasuk.setBackground(new java.awt.Color(255, 255, 255));
        tambahBarangMasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 48, 88));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Masuk");

        t_no.setBorder(null);
        t_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_noActionPerformed(evt);
            }
        });

        t_tanggal.setBorder(null);
        t_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tanggalActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tbl_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sementaraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_sementara);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 116, 130)));

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 140, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 48, 88));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Distributor");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("ID Distributor");

        t_iddis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Nama Distributor");

        t_namadis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_namadis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namadisActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 48, 88));
        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(t_iddis, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(t_namadis))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_namadis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_iddis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 116, 130)));

        kGradientPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel5.setkEndColor(new java.awt.Color(0, 140, 255));
        kGradientPanel5.setkStartColor(new java.awt.Color(0, 48, 88));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Barang");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Kode Barang");

        t_kodbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Nama Barang");

        t_nambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Harga");

        t_harbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        t_jumbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_jumbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_jumbarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Jumlah");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Subtotal");

        t_subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_subtotalActionPerformed(evt);
            }
        });

        t_satuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Satuan");

        jButton2.setBackground(new java.awt.Color(0, 48, 88));
        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(t_kodbar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(t_nambar)
                    .addComponent(t_satuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addComponent(t_harbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addComponent(t_jumbar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(t_subtotal))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_kodbar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_harbar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nambar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_jumbar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Barang Masuk");

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        bt_tambahdata1.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MousePressed(evt);
            }
        });
        bt_tambahdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata1KeyPressed(evt);
            }
        });

        bt_tambah.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambah.setText("TAMBAH");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdata1Layout = new javax.swing.GroupLayout(bt_tambahdata1);
        bt_tambahdata1.setLayout(bt_tambahdata1Layout);
        bt_tambahdata1Layout.setHorizontalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_tambah)
                .addGap(30, 30, 30))
        );
        bt_tambahdata1Layout.setVerticalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_hapusdata2.setBackground(new java.awt.Color(0, 48, 88));
        bt_hapusdata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusdata2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusdata2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusdata2MousePressed(evt);
            }
        });
        bt_hapusdata2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdata2KeyPressed(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setText("BATAL");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Delete_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_hapusdata2Layout = new javax.swing.GroupLayout(bt_hapusdata2);
        bt_hapusdata2.setLayout(bt_hapusdata2Layout);
        bt_hapusdata2Layout.setHorizontalGroup(
            bt_hapusdata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusdata2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_batal)
                .addGap(30, 30, 30))
        );
        bt_hapusdata2Layout.setVerticalGroup(
            bt_hapusdata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusdata2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_hapusdata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Total Masuk");

        lb_tobar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lb_tobar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_tobar.setText("Total");

        bt_perbaruisem.setBackground(new java.awt.Color(0, 129, 236));
        bt_perbaruisem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_perbaruisemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_perbaruisemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_perbaruisemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_perbaruisemMousePressed(evt);
            }
        });
        bt_perbaruisem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_perbaruisemKeyPressed(evt);
            }
        });

        bt_batal1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_batal1.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_batal1.setText("PERBARUI");

        javax.swing.GroupLayout bt_perbaruisemLayout = new javax.swing.GroupLayout(bt_perbaruisem);
        bt_perbaruisem.setLayout(bt_perbaruisemLayout);
        bt_perbaruisemLayout.setHorizontalGroup(
            bt_perbaruisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_perbaruisemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_batal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_perbaruisemLayout.setVerticalGroup(
            bt_perbaruisemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_perbaruisemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_hapusem.setBackground(new java.awt.Color(0, 129, 236));
        bt_hapusem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusemMousePressed(evt);
            }
        });
        bt_hapusem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusemKeyPressed(evt);
            }
        });

        bt_batal3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_batal3.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_batal3.setText("HAPUS");

        javax.swing.GroupLayout bt_hapusemLayout = new javax.swing.GroupLayout(bt_hapusem);
        bt_hapusem.setLayout(bt_hapusemLayout);
        bt_hapusemLayout.setHorizontalGroup(
            bt_hapusemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_batal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_hapusemLayout.setVerticalGroup(
            bt_hapusemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_batal3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahBarangMasukLayout = new javax.swing.GroupLayout(tambahBarangMasuk);
        tambahBarangMasuk.setLayout(tambahBarangMasukLayout);
        tambahBarangMasukLayout.setHorizontalGroup(
            tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapusdata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangMasukLayout.createSequentialGroup()
                                .addComponent(lb_tobar, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addComponent(bt_perbaruisem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapusem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        tambahBarangMasukLayout.setVerticalGroup(
            tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_hapusdata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(lb_tobar)))
                .addGap(16, 16, 16)
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_perbaruisem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_hapusem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahBarangMasuk, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_BarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BarangMasukMouseClicked
        int row = tbl_BarangMasuk.getSelectedRow();
        String id = tbl_BarangMasuk.getValueAt(row, 0).toString();
        pn_detail.setVisible(true);
        List<Model_DetBarangMasuk> list = servis_detmasuk.getData(id);
        tblModel_detmasuk.setData(list);
    }//GEN-LAST:event_tbl_BarangMasukMouseClicked

    private void t_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tanggalActionPerformed

    private void t_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_noActionPerformed

    private void t_namadisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namadisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namadisActionPerformed

    private void t_jumbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_jumbarActionPerformed
        String kode = t_kodbar.getText();
        String nama = t_nambar.getText();
                
        int jumlah;
        Long harga, subtotal;
        harga       = Long.parseLong(t_harbar.getText());
        jumlah      = Integer.parseInt(t_jumbar.getText());
        subtotal    = harga * jumlah;
        t_subtotal.setText(Long.toString(subtotal));
        
        Model_Barang brg = new Model_Barang();
        Model_DetBarangMasuk det_masuk = new Model_DetBarangMasuk();
        Model_BarangMasuk masuk = new Model_BarangMasuk();
        Model_SemBarangMasuk smt = new Model_SemBarangMasuk();
        
        brg.setKode_barang(kode);
        brg.setNama_barang(nama);
        brg.setHarga(harga);
        
        det_masuk.setJml_masuk(jumlah);
        det_masuk.setSubtotal_masuk(subtotal);
        
        smt.setMdl_barang(brg);
        smt.setMdl_detmasuk(det_masuk);
        
        
        servis.tambahData(smt);
        servis_detmasuk.sumTotal(det_masuk);
        lb_tobar.setText(det_masuk.getSubtotal_masuk().toString());
        
        loadDataSementara();
        
        //sumSubTotal();
        
        if(JOptionPane.showConfirmDialog(this, "Mau Tambah Barang?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            aktif();
            bersihBarang();
            t_kodbar.requestFocus();
            
        }else{
            bersihBarang();
            //t_bayar.setEditable(true);
            //t_bayar.requestFocus();
        }
    }//GEN-LAST:event_t_jumbarActionPerformed

    private void t_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subtotalActionPerformed

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahBarangMasuk);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambah.setText("SIMPAN");
        t_no.setText(servis_masuk.nomor());
        t_namadis.setEnabled(false);
        t_tanggal.setEnabled(false);
        t_kodbar.setEnabled(false);
        setTanggal();

        if(bt_data.getText().equals("UBAH"))
        {
            dataTabel();
            //lb_nb.setVisible(false);

        }
    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_tambahdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseEntered
        bt_tambahdata.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_tambahdataMouseEntered

    private void bt_tambahdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseExited
        bt_tambahdata.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_tambahdataMouseExited

    private void bt_tambahdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMousePressed
        bt_tambahdata.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_tambahdataMousePressed

    private void bt_tambahdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdataKeyPressed

    }//GEN-LAST:event_bt_tambahdataKeyPressed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked
        if(bt_tambah.getText().equals("TAMBAH"))
        {
            tambahData();
            bt_tambah.setText("SIMPAN");
        } else if(bt_tambah.getText().equals("SIMPAN"))
        {
            simpanData();
            
            String no = t_no.getText();
            servis_lap.lapBarangMasuk(no);
            resetForm();
            loadDataSementara();
        }
    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_tambahdata1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseEntered
        bt_tambahdata1.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_tambahdata1MouseEntered

    private void bt_tambahdata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseExited
        bt_tambahdata1.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_tambahdata1MouseExited

    private void bt_tambahdata1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MousePressed
        bt_tambahdata1.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_tambahdata1MousePressed

    private void bt_tambahdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata1KeyPressed

    private void bt_hapusdata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata2MouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata2MouseClicked

    private void bt_hapusdata2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata2MouseEntered
        //bt_hapusdata.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_hapusdata2MouseEntered

    private void bt_hapusdata2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata2MouseExited
        //bt_hapusdata.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_hapusdata2MouseExited

    private void bt_hapusdata2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata2MousePressed
        //bt_hapusdata.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_hapusdata2MousePressed

    private void bt_hapusdata2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdata2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdata2KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean closable = true;
        Data_Distributor datdis = new Data_Distributor(null, closable);
        datdis.setVisible(true);

        t_iddis.setText     (datdis.dst.getId_distributor());
        t_namadis.setText   (datdis.dst.getNama_distributor());

        t_kodbar.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean closable = true;
        Data_Barang datbar = new Data_Barang(null, closable);
        datbar.setVisible(true);

        t_kodbar.setText    (datbar.brg.getKode_barang());
        t_nambar.setText    (datbar.brg.getNama_barang());
        t_satuan.setText    (datbar.brg.getSatuan());
        t_harbar.setText    (datbar.brg.getHarga().toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_perbaruisemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perbaruisemMouseClicked
        perbaruiData();
    }//GEN-LAST:event_bt_perbaruisemMouseClicked

    private void bt_perbaruisemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perbaruisemMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_perbaruisemMouseEntered

    private void bt_perbaruisemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perbaruisemMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_perbaruisemMouseExited

    private void bt_perbaruisemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perbaruisemMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_perbaruisemMousePressed

    private void bt_perbaruisemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_perbaruisemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_perbaruisemKeyPressed

    private void bt_hapusemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusemMouseClicked
        hapusDataSementara();
        bersihBarang();
    }//GEN-LAST:event_bt_hapusemMouseClicked

    private void bt_hapusemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusemMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusemMouseEntered

    private void bt_hapusemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusemMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusemMouseExited

    private void bt_hapusemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusemMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusemMousePressed

    private void bt_hapusemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusemKeyPressed

    private void tbl_sementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sementaraMouseClicked
        int row = tbl_sementara.getSelectedRow();

        t_kodbar.setEnabled(false);
        t_nambar.setEnabled(false);
        t_satuan.setEnabled(false);
        t_harbar.setEnabled(false);
        t_subtotal.setEnabled(false);
        
        t_kodbar.setText   (tbl_sementara.getModel().getValueAt(row, 0).toString());
        t_nambar.setText   (tbl_sementara.getModel().getValueAt(row, 1).toString());
        //t_satuan.setText   (tbl_sementara.getModel().getValueAt(row, 2).toString());
        t_harbar.setText   (tbl_sementara.getModel().getValueAt(row, 2).toString());
        t_jumbar.setText   (tbl_sementara.getModel().getValueAt(row, 3).toString());
        t_subtotal.setText (tbl_sementara.getModel().getValueAt(row, 4).toString());
        
        t_jumbar.setEnabled(true);
        t_satuan.setVisible(false);
        jLabel22.setVisible(false);
    }//GEN-LAST:event_tbl_sementaraMouseClicked

    private void dataBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBarangMasukMouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_dataBarangMasukMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        tampilPanel();
        pn_detail.setVisible(false);
        loadData();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void bt_tambahdata5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata5MouseClicked
        int row = tbl_BarangMasuk.getSelectedRow();
        String no = tbl_BarangMasuk.getModel().getValueAt(row, 0).toString();
        servis_lap.lapBarangMasuk(no);
    }//GEN-LAST:event_bt_tambahdata5MouseClicked

    private void bt_tambahdata5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata5MouseEntered

    private void bt_tambahdata5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata5MouseExited

    private void bt_tambahdata5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata5MousePressed

    private void bt_tambahdata5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata5KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_batal;
    private javax.swing.JLabel bt_batal1;
    private javax.swing.JLabel bt_batal3;
    private javax.swing.JLabel bt_data;
    private javax.swing.JLabel bt_data4;
    private javax.swing.JPanel bt_hapusdata2;
    private javax.swing.JPanel bt_hapusem;
    private javax.swing.JPanel bt_perbaruisem;
    private javax.swing.JLabel bt_tambah;
    private javax.swing.JPanel bt_tambahdata;
    private javax.swing.JPanel bt_tambahdata1;
    private javax.swing.JPanel bt_tambahdata5;
    private javax.swing.JPanel dataBarangMasuk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_tobar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JTextField t_cari;
    public javax.swing.JTextField t_harbar;
    public javax.swing.JTextField t_iddis;
    public javax.swing.JTextField t_jumbar;
    public javax.swing.JTextField t_kodbar;
    public javax.swing.JTextField t_namadis;
    public javax.swing.JTextField t_nambar;
    private javax.swing.JTextField t_no;
    public javax.swing.JTextField t_satuan;
    public javax.swing.JTextField t_subtotal;
    private javax.swing.JTextField t_tanggal;
    private javax.swing.JPanel tambahBarangMasuk;
    private javax.swing.JTable tbl_BarangMasuk;
    private javax.swing.JTable tbl_detail;
    private javax.swing.JTable tbl_sementara;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        //bt_hapusdata.setVisible(false);
        
        List<Model_BarangMasuk> list = servis_masuk.getData();
        tblModel_masuk.setData(list);
    }

    private void pencarian() {
        List<Model_BarangMasuk> list = servis_masuk.pencarian(t_cari.getText());
        tblModel_masuk.setData(list);
    }
    
    

    private void resetForm() {
        t_no.setText("");
        t_tanggal.setText("");
        t_iddis.setText("");
        t_namadis.setText("");
        t_kodbar.setText("");
        t_nambar.setText("");
        t_satuan.setText("");
        t_harbar.setText("");
        t_jumbar.setText("");
        t_subtotal.setText("");
        lb_tobar.setText("");

    }
    
    private void nonAktif(){
        t_no.setEnabled(false);
        t_iddis.setEnabled(false);
    }
    
    private void aktif(){
    }

    private void perbaruiData() {
        int index = tbl_sementara.getSelectedRow();
        if (index!=-1) {
            Model_SemBarangMasuk modsem = tblModel.getData(tbl_sementara.convertRowIndexToModel(index));
             
            String kode_barang  = t_kodbar.getText();
            String nama_barang  = t_nambar.getText();
            Long harga          = Long.parseLong(t_harbar.getText());
            int jumlah          = Integer.parseInt(t_jumbar.getText());
            Long subtotal       = Long.parseLong(t_subtotal.getText());
                    
            Model_SemBarangMasuk smt = new Model_SemBarangMasuk();
            Model_Barang brg = new Model_Barang();
            Model_DetBarangMasuk det_masuk = new Model_DetBarangMasuk();
            
            brg.setKode_barang(kode_barang);
            brg.setNama_barang(nama_barang);
            //brg.setSatuan(satuan);
            brg.setHarga(harga);
            det_masuk.setJml_masuk(jumlah);
            det_masuk.setSubtotal_masuk(subtotal);
            
            smt.setMdl_barang(brg);
            smt.setMdl_detmasuk(det_masuk);
                
            servis.perbaruiData(smt);
            tblModel.perbaruiData(index, smt);
            loadDataSementara();
            bersihBarang();
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diperbarui");
        }    
        
    }

    private void dataTabel(){
        //dataBarangMasuk.setVisible(false);
        //tambahBarangMasuk.setVisible(true);
        
        int row = tbl_BarangMasuk.getSelectedRow();

        t_iddis.setEnabled(true);
        t_no.setEnabled(false);

        t_no.setText        (tbl_BarangMasuk.getModel().getValueAt(row, 0).toString());
        t_iddis.setText     (tbl_BarangMasuk.getModel().getValueAt(row, 1).toString());

        aktif();
        //bt_tambah.setText("PERBARUI");
        //bt_batal.setVisible(true);
    }
    
    private void tampilPanel(){
        mainPanel.removeAll();
        String Id = lb_id.getText();
        mainPanel.add(new Form_BarangMasuk(Id));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void hapusDataSementara() {
        int index = tbl_sementara.getSelectedRow();
        if (index!=-1) {
            Model_SemBarangMasuk smt = tblModel.getData(tbl_sementara.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(smt);
                tblModel.hapusData(index);
                loadDataSementara();
                
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");
        
        }
    }
    
    private void tambahData(){
        String no   = t_no.getText();
            
        Model_BarangMasuk masuk = new Model_BarangMasuk();    
        masuk.setNo_masuk(no);
        
        t_no.setText(servis_masuk.nomor());
        setTanggal();
    }
    void setTanggal(){
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
        t_tanggal.setText(kal.format(sekarang));
    }

    
    private void loadDataSementara() {
        List<Model_SemBarangMasuk> list = servis.getData();
        tblModel.setData(list);
    }

    private void bersihBarang() {
        t_kodbar.setText("");
        t_nambar.setText("");
        t_satuan.setText("");
        t_harbar.setText("");
        t_jumbar.setText("");
        t_subtotal.setText("");
    }

    private void simpanData() {
        String no_masuk = t_no.getText();
        String tgl_masuk = t_tanggal.getText();
        String kode = t_kodbar.getText();
        String nama = t_nambar.getText();
        String id_dis = t_iddis.getText();
        String id_peng = lb_id.getText();
        String status = "Sedang di masuk";
        
//        int jumlah      = Integer.parseInt(t_jumbar.getText());
//        Long subtotal   = Long.parseLong(t_subtotal.getText());
        Long total      = Long.parseLong(lb_tobar.getText());
        
        Model_Barang brg = new Model_Barang();
        Model_Distributor dst = new Model_Distributor();
        Model_Pengguna pgn = new Model_Pengguna();
        Model_DetBarangMasuk det_masuk = new Model_DetBarangMasuk();
        Model_BarangMasuk masuk = new Model_BarangMasuk();
        
        // Simpan Tabel BarangMasuk
        masuk.setNo_masuk(no_masuk);
        masuk.setTgl_masuk(tgl_masuk);
        masuk.setTotal_masuk(total);
        dst.setId_distributor(id_dis);
        pgn.setId_pengguna(id_peng);
        
        
        masuk.setMdl_dis(dst);
        masuk.setMdl_peng(pgn);
        
        det_masuk.setMdl_masuk(masuk);
        det_masuk.setMdl_barang(brg);
        
        servis_masuk.tambahData(masuk);
        servis_detmasuk.tambahData(det_masuk);
        servis_detmasuk.hapusSementara(det_masuk);
        tblModel_masuk.tambahData(masuk);
        
        //tampilPanel();
    }

    
}
