/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.Koneksi;
import DAO.DAO_Barang;
import DAO.DAO_DetPemesanan;
import DAO.DAO_Laporan;
import DAO.DAO_Pemesanan;
import DAO.DAO_SemPemesanan;
import Model.Model_Barang;
import Model.Model_DetPemesanan;
import Model.Model_Distributor;
import Model.Model_JenisBarang;
import Model.Model_Pemesanan;
import Model.Model_Pengguna;
import Model.Model_SemPemesanan;
import Service.Service_Barang;
import Service.Service_DetPemesanan;
import Service.Service_Laporan;
import Service.Service_Pemesanan;
import Service.Service_SemPemesanan;
import TableModel.TblMod_Barang;
import TableModel.TblMod_DetPemesanan;
import TableModel.TblMod_Pemesanan;
import TableModel.TblMod_SemPemesanan;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kelompok 4
 */
public class Form_LaporanPemesanan extends javax.swing.JPanel {
    
    private Connection conn;

    private Service_Pemesanan servis_psn = new DAO_Pemesanan();
    private Service_DetPemesanan servis_detpsn = new DAO_DetPemesanan();
    
    private TblMod_Pemesanan tblModel_psn = new TblMod_Pemesanan();
    private TblMod_DetPemesanan tblModel_detpsn = new TblMod_DetPemesanan();
    
    private Service_SemPemesanan servis = new DAO_SemPemesanan();
    private TblMod_SemPemesanan tblModel = new TblMod_SemPemesanan();
    
    private Service_Laporan servis_lap = new DAO_Laporan();
    
    public Form_LaporanPemesanan(String Id) {
        initComponents();
        
        conn = Koneksi.getConnection();
    }
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataLapPesan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pn_pertransaksi1 = new javax.swing.JPanel();
        pn_pertransaksi = new javax.swing.JPanel();
        cetak_notrans = new javax.swing.JPanel();
        bt_cetak = new javax.swing.JLabel();
        t_no = new javax.swing.JTextField();
        brw_transaksi = new javax.swing.JButton();
        bt_tambahdata6 = new javax.swing.JPanel();
        bt_data5 = new javax.swing.JLabel();
        pn_perperiode = new javax.swing.JPanel();
        cetak_periode = new javax.swing.JPanel();
        bt_cetak2 = new javax.swing.JLabel();
        jdate_awal = new com.toedter.calendar.JDateChooser();
        jdate_akhir = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn_perbulan = new javax.swing.JPanel();
        cetak_perbulan = new javax.swing.JPanel();
        bt_cetak3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbx_bulan = new javax.swing.JComboBox<>();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        pn_perdistributor = new javax.swing.JPanel();
        cetak_distributor = new javax.swing.JPanel();
        bt_cetak1 = new javax.swing.JLabel();
        t_dis = new javax.swing.JTextField();
        brw_distributor = new javax.swing.JButton();
        pn_lap = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataLapPesan.setBackground(new java.awt.Color(255, 255, 255));
        dataLapPesan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));
        dataLapPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataLapPesanMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Laporan Pemesanan Barang");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        lb_id.setForeground(new java.awt.Color(255, 255, 255));
        lb_id.setText("lb_id");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Laporan --", "Per Transaksi", "Per Distributor", "Per Periode", "Per Bulan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 321, 35));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Pillih Jenis Laporan ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pn_pertransaksi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        javax.swing.GroupLayout pn_pertransaksi1Layout = new javax.swing.GroupLayout(pn_pertransaksi1);
        pn_pertransaksi1.setLayout(pn_pertransaksi1Layout);
        pn_pertransaksi1Layout.setHorizontalGroup(
            pn_pertransaksi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        pn_pertransaksi1Layout.setVerticalGroup(
            pn_pertransaksi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jPanel1.add(pn_pertransaksi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, 140));

        pn_pertransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        cetak_notrans.setBackground(new java.awt.Color(0, 48, 88));
        cetak_notrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetak_notransMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cetak_notransMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cetak_notransMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cetak_notransMousePressed(evt);
            }
        });
        cetak_notrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cetak_notransKeyPressed(evt);
            }
        });

        bt_cetak.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cetak.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cetak.setText("CETAK");

        javax.swing.GroupLayout cetak_notransLayout = new javax.swing.GroupLayout(cetak_notrans);
        cetak_notrans.setLayout(cetak_notransLayout);
        cetak_notransLayout.setHorizontalGroup(
            cetak_notransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetak_notransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        cetak_notransLayout.setVerticalGroup(
            cetak_notransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetak_notransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t_no.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_no.setText("     No Transaksi");

        brw_transaksi.setText("...");
        brw_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brw_transaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_pertransaksiLayout = new javax.swing.GroupLayout(pn_pertransaksi);
        pn_pertransaksi.setLayout(pn_pertransaksiLayout);
        pn_pertransaksiLayout.setHorizontalGroup(
            pn_pertransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pertransaksiLayout.createSequentialGroup()
                .addGroup(pn_pertransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_pertransaksiLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(cetak_notrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(brw_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_pertransaksiLayout.setVerticalGroup(
            pn_pertransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_pertransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pertransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brw_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(cetak_notrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pn_pertransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, 140));

        bt_tambahdata6.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MousePressed(evt);
            }
        });
        bt_tambahdata6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata6KeyPressed(evt);
            }
        });

        bt_data5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data5.setForeground(new java.awt.Color(255, 255, 255));
        bt_data5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_data5.setText("KEMBALI");

        javax.swing.GroupLayout bt_tambahdata6Layout = new javax.swing.GroupLayout(bt_tambahdata6);
        bt_tambahdata6.setLayout(bt_tambahdata6Layout);
        bt_tambahdata6Layout.setHorizontalGroup(
            bt_tambahdata6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_data5, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_tambahdata6Layout.setVerticalGroup(
            bt_tambahdata6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_data5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(bt_tambahdata6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        pn_perperiode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        cetak_periode.setBackground(new java.awt.Color(0, 48, 88));
        cetak_periode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetak_periodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cetak_periodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cetak_periodeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cetak_periodeMousePressed(evt);
            }
        });
        cetak_periode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cetak_periodeKeyPressed(evt);
            }
        });

        bt_cetak2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cetak2.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cetak2.setText("CETAK");

        javax.swing.GroupLayout cetak_periodeLayout = new javax.swing.GroupLayout(cetak_periode);
        cetak_periode.setLayout(cetak_periodeLayout);
        cetak_periodeLayout.setHorizontalGroup(
            cetak_periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetak_periodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        cetak_periodeLayout.setVerticalGroup(
            cetak_periodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetak_periodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Dari Tanggal");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Sampai Tanggal");

        javax.swing.GroupLayout pn_perperiodeLayout = new javax.swing.GroupLayout(pn_perperiode);
        pn_perperiode.setLayout(pn_perperiodeLayout);
        pn_perperiodeLayout.setHorizontalGroup(
            pn_perperiodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perperiodeLayout.createSequentialGroup()
                .addGroup(pn_perperiodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_perperiodeLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(cetak_periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_perperiodeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jdate_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jdate_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pn_perperiodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(34, 34, 34))
        );
        pn_perperiodeLayout.setVerticalGroup(
            pn_perperiodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_perperiodeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_perperiodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_perperiodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdate_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cetak_periode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pn_perperiode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, 140));

        pn_perbulan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        cetak_perbulan.setBackground(new java.awt.Color(0, 48, 88));
        cetak_perbulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetak_perbulanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cetak_perbulanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cetak_perbulanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cetak_perbulanMousePressed(evt);
            }
        });
        cetak_perbulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cetak_perbulanKeyPressed(evt);
            }
        });

        bt_cetak3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cetak3.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cetak3.setText("CETAK");

        javax.swing.GroupLayout cetak_perbulanLayout = new javax.swing.GroupLayout(cetak_perbulan);
        cetak_perbulan.setLayout(cetak_perbulanLayout);
        cetak_perbulanLayout.setHorizontalGroup(
            cetak_perbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetak_perbulanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        cetak_perbulanLayout.setVerticalGroup(
            cetak_perbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetak_perbulanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Bulan");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Tahun");

        cbx_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Bulan --", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout pn_perbulanLayout = new javax.swing.GroupLayout(pn_perbulan);
        pn_perbulan.setLayout(pn_perbulanLayout);
        pn_perbulanLayout.setHorizontalGroup(
            pn_perbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perbulanLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(cetak_perbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_perbulanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbx_bulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_perbulanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(34, 34, 34))
        );
        pn_perbulanLayout.setVerticalGroup(
            pn_perbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_perbulanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_perbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_perbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx_bulan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cetak_perbulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pn_perbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, 140));

        pn_perdistributor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        cetak_distributor.setBackground(new java.awt.Color(0, 48, 88));
        cetak_distributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetak_distributorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cetak_distributorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cetak_distributorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cetak_distributorMousePressed(evt);
            }
        });
        cetak_distributor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cetak_distributorKeyPressed(evt);
            }
        });

        bt_cetak1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cetak1.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cetak1.setText("CETAK");

        javax.swing.GroupLayout cetak_distributorLayout = new javax.swing.GroupLayout(cetak_distributor);
        cetak_distributor.setLayout(cetak_distributorLayout);
        cetak_distributorLayout.setHorizontalGroup(
            cetak_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetak_distributorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        cetak_distributorLayout.setVerticalGroup(
            cetak_distributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetak_distributorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t_dis.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_dis.setText("     Distributor");

        brw_distributor.setText("...");
        brw_distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brw_distributorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_perdistributorLayout = new javax.swing.GroupLayout(pn_perdistributor);
        pn_perdistributor.setLayout(pn_perdistributorLayout);
        pn_perdistributorLayout.setHorizontalGroup(
            pn_perdistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_perdistributorLayout.createSequentialGroup()
                .addGroup(pn_perdistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_perdistributorLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(cetak_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(brw_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_perdistributorLayout.setVerticalGroup(
            pn_perdistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_perdistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_perdistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brw_distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(cetak_distributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pn_perdistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, 140));

        javax.swing.GroupLayout pn_lapLayout = new javax.swing.GroupLayout(pn_lap);
        pn_lap.setLayout(pn_lapLayout);
        pn_lapLayout.setHorizontalGroup(
            pn_lapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pn_lapLayout.setVerticalGroup(
            pn_lapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dataLapPesanLayout = new javax.swing.GroupLayout(dataLapPesan);
        dataLapPesan.setLayout(dataLapPesanLayout);
        dataLapPesanLayout.setHorizontalGroup(
            dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLapPesanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataLapPesanLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pn_lap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(dataLapPesanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                        .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dataLapPesanLayout.setVerticalGroup(
            dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLapPesanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_lap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(dataLapPesan, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void dataLapPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataLapPesanMouseClicked
//        tampilPanel();
//        loadData();
//        resetForm();
    }//GEN-LAST:event_dataLapPesanMouseClicked

    private void cetak_notransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMouseClicked
        pn_lap.removeAll();
        String no = t_no.getText();
        servis_lap.lapSuratPemesananBarangPerTransaksi(pn_lap, no);
    }//GEN-LAST:event_cetak_notransMouseClicked

    private void cetak_notransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransMouseEntered

    private void cetak_notransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransMouseExited

    private void cetak_notransMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransMousePressed

    private void cetak_notransKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cetak_notransKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransKeyPressed

    private void bt_tambahdata6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MouseClicked
        tampilPanel();
    }//GEN-LAST:event_bt_tambahdata6MouseClicked

    private void bt_tambahdata6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6MouseEntered

    private void bt_tambahdata6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6MouseExited

    private void bt_tambahdata6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6MousePressed

    private void bt_tambahdata6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6KeyPressed

    private void brw_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brw_transaksiActionPerformed
        boolean closable = true;
        Data_Pemesanan dat_pes = new Data_Pemesanan(null, closable);
        dat_pes.setVisible(true);

        t_no.setText     (dat_pes.psn.getNo_pesan());

        bt_cetak.requestFocus();
    }//GEN-LAST:event_brw_transaksiActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem()=="-- Pilih Jenis Laporan --"){
            pn_pertransaksi1.setVisible(true);
            pn_pertransaksi.setVisible(false);
            pn_perperiode.setVisible(false);
            pn_perbulan.setVisible(false);
            pn_perdistributor.setVisible(false);
        }else if(jComboBox1.getSelectedItem()=="Per Transaksi"){
            pn_pertransaksi1.setVisible(false);
            pn_pertransaksi.setVisible(true);
            pn_perperiode.setVisible(false);
            pn_perbulan.setVisible(false);
            pn_perdistributor.setVisible(false);
        }else if(jComboBox1.getSelectedItem()=="Per Periode"){
            pn_pertransaksi1.setVisible(false);
            pn_pertransaksi.setVisible(false);
            pn_perperiode.setVisible(true);
            pn_perbulan.setVisible(false);
            pn_perdistributor.setVisible(false);
        }else if(jComboBox1.getSelectedItem()=="Per Bulan"){
            pn_pertransaksi1.setVisible(false);
            pn_pertransaksi.setVisible(false);
            pn_perperiode.setVisible(false);
            pn_perbulan.setVisible(true);
            pn_perdistributor.setVisible(false);
        }else if(jComboBox1.getSelectedItem()=="Per Distributor"){
            pn_pertransaksi1.setVisible(false);
            pn_pertransaksi.setVisible(false);
            pn_perperiode.setVisible(false);
            pn_perbulan.setVisible(false);
            pn_perdistributor.setVisible(true);
        } 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cetak_periodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_periodeMouseClicked
        pn_lap.removeAll();
        
        String tgl = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tgl);
        String tgl1 = String.valueOf(fm.format(jdate_awal.getDate()));
        String tgl2 = String.valueOf(fm.format(jdate_akhir.getDate()));
        
        servis_lap.lapPemesananBarangPeriode(pn_lap, tgl1, tgl2);
    }//GEN-LAST:event_cetak_periodeMouseClicked

    private void cetak_periodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_periodeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_periodeMouseEntered

    private void cetak_periodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_periodeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_periodeMouseExited

    private void cetak_periodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_periodeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_periodeMousePressed

    private void cetak_periodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cetak_periodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_periodeKeyPressed

    private void cetak_perbulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_perbulanMouseClicked
        pn_lap.removeAll();
        
        String bulan = cbx_bulan.getSelectedItem().toString();
        int tahun = jYearChooser1.getYear();
        
        servis_lap.lapPemesananBarangPerbulan(pn_lap, bulan, tahun);
    }//GEN-LAST:event_cetak_perbulanMouseClicked

    private void cetak_perbulanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_perbulanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_perbulanMouseEntered

    private void cetak_perbulanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_perbulanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_perbulanMouseExited

    private void cetak_perbulanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_perbulanMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_perbulanMousePressed

    private void cetak_perbulanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cetak_perbulanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_perbulanKeyPressed

    private void cetak_distributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_distributorMouseClicked
        pn_lap.removeAll();
        String id_dis = t_dis.getText();
        servis_lap.lapPemesananBarangPerDistributor(pn_lap, id_dis);
    }//GEN-LAST:event_cetak_distributorMouseClicked

    private void cetak_distributorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_distributorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_distributorMouseEntered

    private void cetak_distributorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_distributorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_distributorMouseExited

    private void cetak_distributorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_distributorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_distributorMousePressed

    private void cetak_distributorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cetak_distributorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_distributorKeyPressed

    private void brw_distributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brw_distributorActionPerformed
        boolean closable = true;
        Data_Pemesanan dat_pes = new Data_Pemesanan(null, closable);
        dat_pes.setVisible(true);

        t_dis.setText     (dat_pes.dst.getId_distributor());

        bt_cetak.requestFocus();
    }//GEN-LAST:event_brw_distributorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brw_distributor;
    private javax.swing.JButton brw_transaksi;
    private javax.swing.JLabel bt_cetak;
    private javax.swing.JLabel bt_cetak1;
    private javax.swing.JLabel bt_cetak2;
    private javax.swing.JLabel bt_cetak3;
    private javax.swing.JLabel bt_data5;
    private javax.swing.JPanel bt_tambahdata6;
    private javax.swing.JComboBox<String> cbx_bulan;
    private javax.swing.JPanel cetak_distributor;
    private javax.swing.JPanel cetak_notrans;
    private javax.swing.JPanel cetak_perbulan;
    private javax.swing.JPanel cetak_periode;
    private javax.swing.JPanel dataLapPesan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JDateChooser jdate_akhir;
    private com.toedter.calendar.JDateChooser jdate_awal;
    private javax.swing.JLabel lb_id;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_lap;
    private javax.swing.JPanel pn_perbulan;
    private javax.swing.JPanel pn_perdistributor;
    private javax.swing.JPanel pn_perperiode;
    private javax.swing.JPanel pn_pertransaksi;
    private javax.swing.JPanel pn_pertransaksi1;
    private javax.swing.JTextField t_dis;
    private javax.swing.JTextField t_no;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        List<Model_Pemesanan> list = servis_psn.getData();
        tblModel_psn.setData(list);
    }

    private void tampilPanel(){
        mainPanel.removeAll();
        String Id = lb_id.getText();
        mainPanel.add(new Form_LaporanPemesanan(Id));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

}
