/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author RavenPC
 */
public class Form_Home extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public Form_Home(String Id, String Nama) {
        initComponents();
        
        lb_id.setText(Id);
        lb_nama.setText(Nama);
        lb_id.setVisible(false);
        lb_nama.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        test = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_nama = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        test.setBackground(new java.awt.Color(255, 255, 255));
        test.setPreferredSize(new java.awt.Dimension(700, 800));
        test.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nama.setForeground(new java.awt.Color(255, 255, 255));
        lb_nama.setText("Nama");
        jPanel1.add(lb_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 80, 30));

        lb_id.setForeground(new java.awt.Color(255, 255, 255));
        lb_id.setText("ID");
        jPanel1.add(lb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 44, 80, 30));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 220));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GAMBAR BARUU.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, -110, 1310, 500));

        test.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, 1189, 652));

        add(test, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JPanel test;
    // End of variables declaration//GEN-END:variables
}
