/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Config.Koneksi;
import DAO.DAO_Barang;
import DAO.DAO_DetPemesanan;
import DAO.DAO_Laporan;
import DAO.DAO_Pemesanan;
import DAO.DAO_SemPemesanan;
import Model.Model_Barang;
import Model.Model_DetPemesanan;
import Model.Model_Distributor;
import Model.Model_JenisBarang;
import Model.Model_Pemesanan;
import Model.Model_Pengguna;
import Model.Model_SemPemesanan;
import Service.Service_Barang;
import Service.Service_DetPemesanan;
import Service.Service_Laporan;
import Service.Service_Pemesanan;
import Service.Service_SemPemesanan;
import TableModel.TblMod_Barang;
import TableModel.TblMod_DetPemesanan;
import TableModel.TblMod_Pemesanan;
import TableModel.TblMod_SemPemesanan;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kelompok 4
 */

public class Form_LaporanDataDistributor extends javax.swing.JPanel {
    
    private Connection conn;

    private Service_Laporan servis_lap = new DAO_Laporan();
    
    public Form_LaporanDataDistributor(String Id) {
        initComponents();
        conn = Koneksi.getConnection();        
    }
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataLapPesan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_id = new javax.swing.JLabel();
        pn_lap1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pn_lapbarang1 = new javax.swing.JPanel();
        pn_lapbarang = new javax.swing.JPanel();
        cetak_notrans = new javax.swing.JPanel();
        bt_cetak = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bt_tambahdata6 = new javax.swing.JPanel();
        bt_data5 = new javax.swing.JLabel();
        pn_laptransbarang = new javax.swing.JPanel();
        cetak_notrans1 = new javax.swing.JPanel();
        bt_cetak1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_lap = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataLapPesan.setBackground(new java.awt.Color(255, 255, 255));
        dataLapPesan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));
        dataLapPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataLapPesanMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Laporan Data Distributor");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        lb_id.setForeground(new java.awt.Color(255, 255, 255));
        lb_id.setText("lb_id");

        pn_lap1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Jenis Laporan --", "Laporan Data Distributor", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        pn_lap1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 321, 35));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Pillih Jenis Laporan ");
        pn_lap1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pn_lapbarang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        javax.swing.GroupLayout pn_lapbarang1Layout = new javax.swing.GroupLayout(pn_lapbarang1);
        pn_lapbarang1.setLayout(pn_lapbarang1Layout);
        pn_lapbarang1Layout.setHorizontalGroup(
            pn_lapbarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        pn_lapbarang1Layout.setVerticalGroup(
            pn_lapbarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        pn_lap1.add(pn_lapbarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 320, 140));

        pn_lapbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        cetak_notrans.setBackground(new java.awt.Color(0, 48, 88));
        cetak_notrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetak_notransMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cetak_notransMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cetak_notransMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cetak_notransMousePressed(evt);
            }
        });
        cetak_notrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cetak_notransKeyPressed(evt);
            }
        });

        bt_cetak.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cetak.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cetak.setText("CETAK");

        javax.swing.GroupLayout cetak_notransLayout = new javax.swing.GroupLayout(cetak_notrans);
        cetak_notrans.setLayout(cetak_notransLayout);
        cetak_notransLayout.setHorizontalGroup(
            cetak_notransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetak_notransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        cetak_notransLayout.setVerticalGroup(
            cetak_notransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetak_notransLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 15));
        jLabel7.setText("Laporan Data Master Distributor");

        javax.swing.GroupLayout pn_lapbarangLayout = new javax.swing.GroupLayout(pn_lapbarang);
        pn_lapbarang.setLayout(pn_lapbarangLayout);
        pn_lapbarangLayout.setHorizontalGroup(
            pn_lapbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lapbarangLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(cetak_notrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lapbarangLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(30, 30, 30))
        );
        pn_lapbarangLayout.setVerticalGroup(
            pn_lapbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_lapbarangLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cetak_notrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jLabel7.getAccessibleContext().setAccessibleName("");

        pn_lap1.add(pn_lapbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 320, 140));

        bt_tambahdata6.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata6MousePressed(evt);
            }
        });
        bt_tambahdata6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata6KeyPressed(evt);
            }
        });

        bt_data5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data5.setForeground(new java.awt.Color(255, 255, 255));
        bt_data5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_data5.setText("KEMBALI");

        javax.swing.GroupLayout bt_tambahdata6Layout = new javax.swing.GroupLayout(bt_tambahdata6);
        bt_tambahdata6.setLayout(bt_tambahdata6Layout);
        bt_tambahdata6Layout.setHorizontalGroup(
            bt_tambahdata6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_data5, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        bt_tambahdata6Layout.setVerticalGroup(
            bt_tambahdata6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_data5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_lap1.add(bt_tambahdata6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        pn_laptransbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        cetak_notrans1.setBackground(new java.awt.Color(0, 48, 88));
        cetak_notrans1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetak_notrans1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cetak_notrans1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cetak_notrans1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cetak_notrans1MousePressed(evt);
            }
        });
        cetak_notrans1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cetak_notrans1KeyPressed(evt);
            }
        });

        bt_cetak1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_cetak1.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_cetak1.setText("CETAK");

        javax.swing.GroupLayout cetak_notrans1Layout = new javax.swing.GroupLayout(cetak_notrans1);
        cetak_notrans1.setLayout(cetak_notrans1Layout);
        cetak_notrans1Layout.setHorizontalGroup(
            cetak_notrans1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetak_notrans1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        cetak_notrans1Layout.setVerticalGroup(
            cetak_notrans1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cetak_notrans1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_cetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Laporan Transaksi Barang");

        javax.swing.GroupLayout pn_laptransbarangLayout = new javax.swing.GroupLayout(pn_laptransbarang);
        pn_laptransbarang.setLayout(pn_laptransbarangLayout);
        pn_laptransbarangLayout.setHorizontalGroup(
            pn_laptransbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_laptransbarangLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(cetak_notrans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_laptransbarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(46, 46, 46))
        );
        pn_laptransbarangLayout.setVerticalGroup(
            pn_laptransbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_laptransbarangLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cetak_notrans1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pn_lap1.add(pn_laptransbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 320, 140));

        javax.swing.GroupLayout pn_lapLayout = new javax.swing.GroupLayout(pn_lap);
        pn_lap.setLayout(pn_lapLayout);
        pn_lapLayout.setHorizontalGroup(
            pn_lapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pn_lapLayout.setVerticalGroup(
            pn_lapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dataLapPesanLayout = new javax.swing.GroupLayout(dataLapPesan);
        dataLapPesan.setLayout(dataLapPesanLayout);
        dataLapPesanLayout.setHorizontalGroup(
            dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataLapPesanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataLapPesanLayout.createSequentialGroup()
                        .addComponent(pn_lap1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pn_lap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(dataLapPesanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                        .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dataLapPesanLayout.setVerticalGroup(
            dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataLapPesanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataLapPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_lap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_lap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(dataLapPesan, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void dataLapPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataLapPesanMouseClicked
//        tampilPanel();
//        loadData();
//        resetForm();
    }//GEN-LAST:event_dataLapPesanMouseClicked

    private void cetak_notransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMouseClicked
        pn_lap.removeAll();
        //String no = t_no.getText();
        servis_lap.lapDataDistributor(pn_lap);
    }//GEN-LAST:event_cetak_notransMouseClicked

    private void cetak_notransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransMouseEntered

    private void cetak_notransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransMouseExited

    private void cetak_notransMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notransMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransMousePressed

    private void cetak_notransKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cetak_notransKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notransKeyPressed

    private void bt_tambahdata6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MouseClicked
        tampilPanel();
    }//GEN-LAST:event_bt_tambahdata6MouseClicked

    private void bt_tambahdata6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6MouseEntered

    private void bt_tambahdata6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6MouseExited

    private void bt_tambahdata6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6MousePressed

    private void bt_tambahdata6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata6KeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem()=="-- Pilih Jenis Laporan --"){
            pn_lapbarang1.setVisible(true);
            pn_lapbarang.setVisible(false);
            pn_laptransbarang.setVisible(false);
        }else if(jComboBox1.getSelectedItem()=="Laporan Data Distributor"){
            pn_lapbarang1.setVisible(false);
            pn_lapbarang.setVisible(true);
            pn_laptransbarang.setVisible(false);
//        }else if(jComboBox1.getSelectedItem()=="Laporan Transaksi Pengguna"){
//            pn_lapbarang1.setVisible(false);
//            pn_lapbarang.setVisible(false);
//            pn_laptransbarang.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cetak_notrans1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notrans1MouseClicked
        pn_lap.removeAll();
        servis_lap.lapTransaksiStokBarang(pn_lap);
    }//GEN-LAST:event_cetak_notrans1MouseClicked

    private void cetak_notrans1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notrans1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notrans1MouseEntered

    private void cetak_notrans1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notrans1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notrans1MouseExited

    private void cetak_notrans1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak_notrans1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notrans1MousePressed

    private void cetak_notrans1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cetak_notrans1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cetak_notrans1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_cetak;
    private javax.swing.JLabel bt_cetak1;
    private javax.swing.JLabel bt_data5;
    private javax.swing.JPanel bt_tambahdata6;
    private javax.swing.JPanel cetak_notrans;
    private javax.swing.JPanel cetak_notrans1;
    private javax.swing.JPanel dataLapPesan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_lap;
    private javax.swing.JPanel pn_lap1;
    private javax.swing.JPanel pn_lapbarang;
    private javax.swing.JPanel pn_lapbarang1;
    private javax.swing.JPanel pn_laptransbarang;
    // End of variables declaration//GEN-END:variables

    
    private void tampilPanel(){
        mainPanel.removeAll();
        String Id = lb_id.getText();
        mainPanel.add(new Form_LaporanDataDistributor(Id));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

}
