/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAO_JenisBarang;
import Model.Model_JenisBarang;
import Service.Service_JenisBarang;
import TableModel.TblMod_JenisBarang;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kelompok 4
 */
public class Master_JenisBarang extends javax.swing.JPanel {

    private Service_JenisBarang servis = new DAO_JenisBarang();
    private TblMod_JenisBarang tblModel = new TblMod_JenisBarang();
    
    public Master_JenisBarang() {
        initComponents();
        
        tbl_jenisbarang.setModel(tblModel);
        tbl_jenisbarang.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_jenisbarang.getTableHeader().setOpaque(false);
        tbl_jenisbarang.getTableHeader().setBackground(new Color(0,48,88));
        tbl_jenisbarang.getTableHeader().setForeground(new Color(255,255,255));
        tbl_jenisbarang.setRowHeight(27);
        
        //setLocationRelativeTo(null);
        tbl_jenisbarang.setModel(tblModel);
        loadData();
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataJenisBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jenisbarang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        bt_bataldata2 = new javax.swing.JPanel();
        bt_bataldata = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bt_hapusdata = new javax.swing.JPanel();
        bt_hapus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JPanel();
        bt_data = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tambahJenisBarang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_kodejenis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_namajenis = new javax.swing.JTextField();
        bt_hapusdata1 = new javax.swing.JPanel();
        bt_batal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bt_tambahdata1 = new javax.swing.JPanel();
        bt_tambah = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataJenisBarang.setBackground(new java.awt.Color(255, 255, 255));
        dataJenisBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));

        tbl_jenisbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_jenisbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_jenisbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_jenisbarang);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon_Cari2.png"))); // NOI18N

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        bt_bataldata2.setBackground(new java.awt.Color(0, 48, 88));
        bt_bataldata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_bataldata2MousePressed(evt);
            }
        });
        bt_bataldata2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_bataldata2KeyPressed(evt);
            }
        });

        bt_bataldata.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_bataldata.setForeground(new java.awt.Color(255, 255, 255));
        bt_bataldata.setText("BATAL");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_File_Delete_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_bataldata2Layout = new javax.swing.GroupLayout(bt_bataldata2);
        bt_bataldata2.setLayout(bt_bataldata2Layout);
        bt_bataldata2Layout.setHorizontalGroup(
            bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_bataldata2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_bataldata)
                .addGap(30, 30, 30))
        );
        bt_bataldata2Layout.setVerticalGroup(
            bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_bataldata2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_bataldata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_hapusdata.setBackground(new java.awt.Color(0, 48, 88));
        bt_hapusdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusdataMousePressed(evt);
            }
        });
        bt_hapusdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdataKeyPressed(evt);
            }
        });

        bt_hapus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setText("HAPUS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Delete_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_hapusdataLayout = new javax.swing.GroupLayout(bt_hapusdata);
        bt_hapusdata.setLayout(bt_hapusdataLayout);
        bt_hapusdataLayout.setHorizontalGroup(
            bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusdataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_hapus)
                .addGap(30, 30, 30))
        );
        bt_hapusdataLayout.setVerticalGroup(
            bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_tambahdata.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdataMousePressed(evt);
            }
        });
        bt_tambahdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdataKeyPressed(evt);
            }
        });

        bt_data.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data.setForeground(new java.awt.Color(255, 255, 255));
        bt_data.setText("TAMBAH");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdataLayout = new javax.swing.GroupLayout(bt_tambahdata);
        bt_tambahdata.setLayout(bt_tambahdataLayout);
        bt_tambahdataLayout.setHorizontalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_data)
                .addGap(30, 30, 30))
        );
        bt_tambahdataLayout.setVerticalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Kategori Barang");

        javax.swing.GroupLayout dataJenisBarangLayout = new javax.swing.GroupLayout(dataJenisBarang);
        dataJenisBarang.setLayout(dataJenisBarangLayout);
        dataJenisBarangLayout.setHorizontalGroup(
            dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataJenisBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataJenisBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataJenisBarangLayout.setVerticalGroup(
            dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataJenisBarang, "card2");

        tambahJenisBarang.setBackground(new java.awt.Color(255, 255, 255));
        tambahJenisBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Kode Jenis Barang");

        t_kodejenis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_kodejenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodejenisActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Nama Jenis Barang");

        t_namajenis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namajenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namajenisActionPerformed(evt);
            }
        });

        bt_hapusdata1.setBackground(new java.awt.Color(0, 48, 88));
        bt_hapusdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MousePressed(evt);
            }
        });
        bt_hapusdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdata1KeyPressed(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setText("BATAL");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Delete_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_hapusdata1Layout = new javax.swing.GroupLayout(bt_hapusdata1);
        bt_hapusdata1.setLayout(bt_hapusdata1Layout);
        bt_hapusdata1Layout.setHorizontalGroup(
            bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusdata1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_batal)
                .addGap(30, 30, 30))
        );
        bt_hapusdata1Layout.setVerticalGroup(
            bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusdata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_tambahdata1.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MousePressed(evt);
            }
        });
        bt_tambahdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata1KeyPressed(evt);
            }
        });

        bt_tambah.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambah.setText("TAMBAH");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdata1Layout = new javax.swing.GroupLayout(bt_tambahdata1);
        bt_tambahdata1.setLayout(bt_tambahdata1Layout);
        bt_tambahdata1Layout.setHorizontalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_tambah)
                .addGap(30, 30, 30))
        );
        bt_tambahdata1Layout.setVerticalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Kategori Barang");

        javax.swing.GroupLayout tambahJenisBarangLayout = new javax.swing.GroupLayout(tambahJenisBarang);
        tambahJenisBarang.setLayout(tambahJenisBarangLayout);
        tambahJenisBarangLayout.setHorizontalGroup(
            tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(541, 541, 541))
                    .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                        .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(t_kodejenis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_namajenis, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 744, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        tambahJenisBarangLayout.setVerticalGroup(
            tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_kodejenis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_namajenis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        mainPanel.add(tambahJenisBarang, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void t_kodejenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodejenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodejenisActionPerformed

    private void t_namajenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namajenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namajenisActionPerformed

    private void tbl_jenisbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_jenisbarangMouseClicked
        if(bt_data.getText().equals("TAMBAH"))
        {
            bt_data.setText("UBAH");
            
        }
        bt_hapusdata.setVisible(true);
        bt_bataldata2.setVisible(true);
    }//GEN-LAST:event_tbl_jenisbarangMouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void bt_bataldata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseClicked
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_bataldata2MouseClicked

    private void bt_bataldata2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MouseEntered

    private void bt_bataldata2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MouseExited

    private void bt_bataldata2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MousePressed

    private void bt_bataldata2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_bataldata2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2KeyPressed

    private void bt_hapusdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseClicked
        hapusData();
    }//GEN-LAST:event_bt_hapusdataMouseClicked

    private void bt_hapusdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseEntered
        bt_hapusdata.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_hapusdataMouseEntered

    private void bt_hapusdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseExited
        bt_hapusdata.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_hapusdataMouseExited

    private void bt_hapusdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMousePressed
        bt_hapusdata.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_hapusdataMousePressed

    private void bt_hapusdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdataKeyPressed

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahJenisBarang);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambah.setText("SIMPAN");

        t_kodejenis.setText(servis.nomor());

        if(bt_data.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_tambahdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseEntered
        bt_tambahdata.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_tambahdataMouseEntered

    private void bt_tambahdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseExited
        bt_tambahdata.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_tambahdataMouseExited

    private void bt_tambahdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMousePressed
        bt_tambahdata.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_tambahdataMousePressed

    private void bt_tambahdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdataKeyPressed

    }//GEN-LAST:event_bt_tambahdataKeyPressed

    private void bt_hapusdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1MouseClicked

    private void bt_hapusdata1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseEntered
        bt_hapusdata1.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_hapusdata1MouseEntered

    private void bt_hapusdata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseExited
        bt_hapusdata1.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_hapusdata1MouseExited

    private void bt_hapusdata1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MousePressed
        bt_hapusdata1.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_hapusdata1MousePressed

    private void bt_hapusdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdata1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdata1KeyPressed

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked
        if(bt_tambah.getText().equals("TAMBAH"))
        {
            bt_tambah.setText("SIMPAN");
            t_kodejenis.setText(servis.nomor());

        }
        else if(bt_tambah.getText().equals("SIMPAN"))
        {
            simpanData();

        }
        else if(bt_tambah.getText().equals("PERBARUI"))
        {
            perbaruiData();

        }
    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_tambahdata1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseEntered
        bt_tambahdata1.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_tambahdata1MouseEntered

    private void bt_tambahdata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseExited
        bt_tambahdata1.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_tambahdata1MouseExited

    private void bt_tambahdata1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MousePressed
        bt_tambahdata1.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_tambahdata1MousePressed

    private void bt_tambahdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_batal;
    private javax.swing.JLabel bt_bataldata;
    private javax.swing.JPanel bt_bataldata2;
    private javax.swing.JLabel bt_data;
    private javax.swing.JLabel bt_hapus;
    private javax.swing.JPanel bt_hapusdata;
    private javax.swing.JPanel bt_hapusdata1;
    private javax.swing.JLabel bt_tambah;
    private javax.swing.JPanel bt_tambahdata;
    private javax.swing.JPanel bt_tambahdata1;
    private javax.swing.JPanel dataJenisBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_kodejenis;
    private javax.swing.JTextField t_namajenis;
    private javax.swing.JPanel tambahJenisBarang;
    private javax.swing.JTable tbl_jenisbarang;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bt_hapusdata.setVisible(false);
        bt_bataldata2.setVisible(false);
        List<Model_JenisBarang> list = servis.getData();
        tblModel.setData(list);
    }

    private void pencarian() {
        List<Model_JenisBarang> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
    
    private void resetForm() {
        bt_tambah.requestFocus();
        t_kodejenis.setText("");
        t_namajenis.setText("");
    }

    private void perbaruiData() {
        int index = tbl_jenisbarang.getSelectedRow();
        if (index!=-1) {
            Model_JenisBarang mokat = tblModel.getData(tbl_jenisbarang.convertRowIndexToModel(index));
             
            String kodejenis  = t_kodejenis.getText();
            String namajenis  = t_namajenis.getText();
                    
            Model_JenisBarang jb = new Model_JenisBarang();
            jb.setKode_jenis(kodejenis);
            jb.setNama_jenis(namajenis);
                
            servis.perbaruiData(jb);
            tblModel.perbaruiData(index, jb);
            loadData();
            resetForm();
            
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diperbarui");
        }
    }

    private void hapusData() {
        int index = tbl_jenisbarang.getSelectedRow();
        if (index!=-1) {
            Model_JenisBarang jb = tblModel.getData(tbl_jenisbarang.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(jb);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");
        
        }
    }
    
    private void dataTabel(){
        dataJenisBarang.setVisible(false);
        tambahJenisBarang.setVisible(true);
        
        int row = tbl_jenisbarang.getSelectedRow();

        t_namajenis.setEnabled(true);
        t_kodejenis.setEnabled(false);

        t_kodejenis.setText   (tbl_jenisbarang.getModel().getValueAt(row, 0).toString());
        t_namajenis.setText   (tbl_jenisbarang.getModel().getValueAt(row, 1).toString());

        bt_tambah.setText("PERBARUI");
        bt_batal.setVisible(true);
    }
    
    private void tampilPanel(){
        mainPanel.removeAll();
        mainPanel.add(new Master_JenisBarang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void simpanData() {
        String kode = t_kodejenis.getText();
        String nama = t_namajenis.getText();
        
        Model_JenisBarang jb = new Model_JenisBarang();
        jb.setKode_jenis(kode);
        jb.setNama_jenis(nama);
        
        if(servis.validasiNamaJenisBarang(jb)==true)
        {
            if(validasiInput()==true){
                String kode_jenis   = t_kodejenis.getText();
                String nama_jenis = t_namajenis.getText();

                Model_JenisBarang jbg = new Model_JenisBarang();
                jbg.setKode_jenis(kode_jenis);
                jbg.setNama_jenis(nama_jenis);

                servis.tambahData(jb);
                tblModel.tambahData(jb);
                tampilPanel();
                loadData();
                resetForm();
                bt_tambah.setText("TAMBAH");
            }
        }else
        {
            t_namajenis.requestFocus();
        }
    }
    
    private boolean validasiInput() {
        
            boolean valid = false;
            if (t_kodejenis.getText().trim().isEmpty() )
            {
                JOptionPane.showMessageDialog(null, "Kode Jenis Barang tidak boleh kosong");
            }else if (t_namajenis.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Nama Jenis Barang tidak boleh kosong");
            }else{
                valid = true;
            }
            return valid;
        
    }
}
