/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAO_Barang;
import Model.Model_Barang;
import Model.Model_JenisBarang;
import Service.Service_Barang;
import TableModel.TblMod_Barang;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kelompok 4
 */
public class Master_Barang extends javax.swing.JPanel {

    private Service_Barang servis = new DAO_Barang();
    private TblMod_Barang tblModel = new TblMod_Barang();
    
    public Master_Barang() {
        initComponents();
        
        tbl_barang.setModel(tblModel);
        tbl_barang.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_barang.getTableHeader().setOpaque(false);
        tbl_barang.getTableHeader().setBackground(new Color(0,48,88));
        tbl_barang.getTableHeader().setForeground(new Color(255,255,255));
        tbl_barang.setRowHeight(27);
        
        //setLocationRelativeTo(null);
        tbl_barang.setModel(tblModel);
        loadData();
        resetForm();
        nonAktif();
        bt_data.requestFocus();
    }
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JPanel();
        bt_data = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_hapusdata = new javax.swing.JPanel();
        bt_hapus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bt_bataldata2 = new javax.swing.JPanel();
        bt_bataldata = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tambahBarang = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        t_namajenisbarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_jenisbarang = new javax.swing.JTextField();
        bt_jenisbarang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t_kodebarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_namabarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_stok = new javax.swing.JTextField();
        cbx_satuan = new javax.swing.JComboBox<>();
        bt_tambahdata1 = new javax.swing.JPanel();
        bt_tambah = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bt_hapusdata1 = new javax.swing.JPanel();
        bt_batal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));
        dataBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));

        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_barang.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang);

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon_Cari2.png"))); // NOI18N

        bt_tambahdata.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdataMousePressed(evt);
            }
        });
        bt_tambahdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdataKeyPressed(evt);
            }
        });

        bt_data.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data.setForeground(new java.awt.Color(255, 255, 255));
        bt_data.setText("TAMBAH");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdataLayout = new javax.swing.GroupLayout(bt_tambahdata);
        bt_tambahdata.setLayout(bt_tambahdataLayout);
        bt_tambahdataLayout.setHorizontalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_data)
                .addGap(30, 30, 30))
        );
        bt_tambahdataLayout.setVerticalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_hapusdata.setBackground(new java.awt.Color(0, 48, 88));
        bt_hapusdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusdataMousePressed(evt);
            }
        });
        bt_hapusdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdataKeyPressed(evt);
            }
        });

        bt_hapus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setText("HAPUS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Delete_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_hapusdataLayout = new javax.swing.GroupLayout(bt_hapusdata);
        bt_hapusdata.setLayout(bt_hapusdataLayout);
        bt_hapusdataLayout.setHorizontalGroup(
            bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusdataLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_hapus)
                .addGap(30, 30, 30))
        );
        bt_hapusdataLayout.setVerticalGroup(
            bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Barang");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        bt_bataldata2.setBackground(new java.awt.Color(0, 48, 88));
        bt_bataldata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_bataldata2MousePressed(evt);
            }
        });
        bt_bataldata2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_bataldata2KeyPressed(evt);
            }
        });

        bt_bataldata.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_bataldata.setForeground(new java.awt.Color(255, 255, 255));
        bt_bataldata.setText("BATAL");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_File_Delete_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_bataldata2Layout = new javax.swing.GroupLayout(bt_bataldata2);
        bt_bataldata2.setLayout(bt_bataldata2Layout);
        bt_bataldata2Layout.setHorizontalGroup(
            bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_bataldata2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_bataldata)
                .addGap(30, 30, 30))
        );
        bt_bataldata2Layout.setVerticalGroup(
            bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_bataldata2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_bataldata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(255, 255, 255));
        tambahBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        t_namajenisbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Nama Jenis Barang");

        t_jenisbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        bt_jenisbarang.setBackground(new java.awt.Color(18, 61, 70));
        bt_jenisbarang.setText("...");
        bt_jenisbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_jenisbarangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Kode Jenis Barang");

        t_kodebarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Kode Barang");

        t_namabarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namabarangActionPerformed(evt);
            }
        });
        t_namabarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_namabarangKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Nama Barang");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Satuan");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Harga");

        t_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Stok");

        t_stok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        cbx_satuan.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        cbx_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jenis Satuan -", "Kg", "Buah" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(t_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t_stok, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_harga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_satuan, javax.swing.GroupLayout.Alignment.LEADING, 0, 221, Short.MAX_VALUE)
                            .addComponent(t_namabarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namajenisbarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_jenisbarang, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(bt_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namajenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bt_tambahdata1.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MousePressed(evt);
            }
        });
        bt_tambahdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata1KeyPressed(evt);
            }
        });

        bt_tambah.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambah.setText("TAMBAH");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdata1Layout = new javax.swing.GroupLayout(bt_tambahdata1);
        bt_tambahdata1.setLayout(bt_tambahdata1Layout);
        bt_tambahdata1Layout.setHorizontalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_tambah)
                .addGap(30, 30, 30))
        );
        bt_tambahdata1Layout.setVerticalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_hapusdata1.setBackground(new java.awt.Color(0, 48, 88));
        bt_hapusdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MousePressed(evt);
            }
        });
        bt_hapusdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdata1KeyPressed(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setText("BATAL");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Delete_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_hapusdata1Layout = new javax.swing.GroupLayout(bt_hapusdata1);
        bt_hapusdata1.setLayout(bt_hapusdata1Layout);
        bt_hapusdata1Layout.setHorizontalGroup(
            bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusdata1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_batal)
                .addGap(30, 30, 30))
        );
        bt_hapusdata1Layout.setVerticalGroup(
            bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusdata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Data Barang");

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahBarangLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_jenisbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_jenisbarangActionPerformed
        boolean closable = true;
        Data_JenisBarang djb = new Data_JenisBarang(null, closable);
        djb.setVisible(true);
        
        t_jenisbarang.setText(djb.jb.getKode_jenis());
        t_namajenisbarang.setText(djb.jb.getNama_jenis());
        
        t_namabarang.requestFocus();
        aktif();
        
//        String namakode,kode = "";
//        namakode = t_namajenisbarang.getText().substring(0,3).toUpperCase();
//        kode=kode.concat(namakode);
//        kode=kode.concat("");
//        t_kodebarang.setText(servis.nomor()+kode+servis.nomor2());
//        lb_nb.setVisible(false);
    }//GEN-LAST:event_bt_jenisbarangActionPerformed

    private void t_namabarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_namabarangKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cbx_satuan.requestFocus();
        }
    }//GEN-LAST:event_t_namabarangKeyPressed

    private void t_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namabarangActionPerformed

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked
        if(bt_tambah.getText().equals("TAMBAH"))
        {
            bt_tambah.setText("SIMPAN");
            t_kodebarang.setText(servis.nomor());
            
        }
        else if(bt_tambah.getText().equals("SIMPAN"))
        {
            simpanData();
            
        }
        else if(bt_tambah.getText().equals("PERBARUI"))
        {
            perbaruiData();
            
        }
    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_tambahdata1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseEntered
        bt_tambahdata1.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_tambahdata1MouseEntered

    private void bt_tambahdata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseExited
        bt_tambahdata1.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_tambahdata1MouseExited

    private void bt_tambahdata1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MousePressed
        bt_tambahdata1.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_tambahdata1MousePressed

    private void bt_tambahdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata1KeyPressed

    private void bt_hapusdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1MouseClicked

    private void bt_hapusdata1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseEntered
        bt_hapusdata1.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_hapusdata1MouseEntered

    private void bt_hapusdata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseExited
        bt_hapusdata1.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_hapusdata1MouseExited

    private void bt_hapusdata1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MousePressed
        bt_hapusdata1.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_hapusdata1MousePressed

    private void bt_hapusdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdata1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdata1KeyPressed

    private void bt_hapusdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdataKeyPressed

    private void bt_hapusdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMousePressed
        bt_hapusdata.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_hapusdataMousePressed

    private void bt_hapusdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseExited
        bt_hapusdata.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_hapusdataMouseExited

    private void bt_hapusdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseEntered
        bt_hapusdata.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_hapusdataMouseEntered

    private void bt_hapusdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseClicked
        hapusData();
    }//GEN-LAST:event_bt_hapusdataMouseClicked

    private void bt_tambahdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdataKeyPressed

    }//GEN-LAST:event_bt_tambahdataKeyPressed

    private void bt_tambahdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMousePressed
        bt_tambahdata.setBackground(new Color(1, 28, 51));

    }//GEN-LAST:event_bt_tambahdataMousePressed

    private void bt_tambahdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseExited
        bt_tambahdata.setBackground(new Color(0,48,88));

    }//GEN-LAST:event_bt_tambahdataMouseExited

    private void bt_tambahdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseEntered
        bt_tambahdata.setBackground(new Color(1, 36, 66));

    }//GEN-LAST:event_bt_tambahdataMouseEntered

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambah.setText("SIMPAN");
        bt_jenisbarang.setEnabled(true);
        t_kodebarang.setText(servis.nomor());

        if(bt_data.getText().equals("UBAH"))
        {
            dataTabel();
            //lb_nb.setVisible(false);

        }
    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        if(bt_data.getText().equals("TAMBAH"))
        {
            bt_data.setText("UBAH");

        }
        bt_hapusdata.setVisible(true);
        bt_bataldata2.setVisible(true);

    }//GEN-LAST:event_tbl_barangMouseClicked

    private void bt_bataldata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseClicked
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_bataldata2MouseClicked

    private void bt_bataldata2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MouseEntered

    private void bt_bataldata2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MouseExited

    private void bt_bataldata2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MousePressed

    private void bt_bataldata2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_bataldata2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_batal;
    private javax.swing.JLabel bt_bataldata;
    private javax.swing.JPanel bt_bataldata2;
    private javax.swing.JLabel bt_data;
    private javax.swing.JLabel bt_hapus;
    private javax.swing.JPanel bt_hapusdata;
    private javax.swing.JPanel bt_hapusdata1;
    private javax.swing.JButton bt_jenisbarang;
    private javax.swing.JLabel bt_tambah;
    private javax.swing.JPanel bt_tambahdata;
    private javax.swing.JPanel bt_tambahdata1;
    private javax.swing.JComboBox<String> cbx_satuan;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_harga;
    public javax.swing.JTextField t_jenisbarang;
    private javax.swing.JTextField t_kodebarang;
    private javax.swing.JTextField t_namabarang;
    private javax.swing.JTextField t_namajenisbarang;
    private javax.swing.JTextField t_stok;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTable tbl_barang;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bt_hapusdata.setVisible(false);
        bt_bataldata2.setVisible(false);
        List<Model_Barang> list = servis.getData();
        tblModel.setData(list);
    }

    private void pencarian() {
        List<Model_Barang> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
    
    

    private void resetForm() {
        bt_tambah.requestFocus();
        t_kodebarang.setText("");
        t_jenisbarang.setText("");
        t_namajenisbarang.setText("");
        t_namabarang.setText("");
        cbx_satuan.setSelectedItem(0);
        t_harga.setText("");
        t_stok.setText("");
    }
    
    private void nonAktif(){
        t_kodebarang.setEnabled(false);
        t_jenisbarang.setEnabled(false);
        bt_jenisbarang.setEnabled(false);
        t_namajenisbarang.setEnabled(false);
        t_namabarang.setEnabled(false);
        cbx_satuan.setEnabled(false);
        t_harga.setEnabled(false);
        t_stok.setEnabled(false);
    }
    
    private void aktif(){
        t_namabarang.setEnabled(true);
        t_namabarang.setEnabled(true);
        cbx_satuan.setEnabled(true);
        t_harga.setEnabled(true);
        t_stok.setEnabled(true);
    }

    private void perbaruiData() {
        int index = tbl_barang.getSelectedRow();
        if (index!=-1) {
            Model_Barang mobar = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
             
            if(validasiInput()==true){
                String kode_barang  = t_kodebarang.getText();
                String kode_jenis   = t_jenisbarang.getText();
                //String nama_jenis   = t_namajenisbarang.getText();
                String nama_barang  = t_namabarang.getText();
                String satuan       = cbx_satuan.getSelectedItem().toString();
                Long harga          = Long.parseLong(t_harga.getText());
                int stok         = Integer.parseInt(t_stok.getText());

                Model_Barang brg = new Model_Barang();
                Model_JenisBarang jbr = new Model_JenisBarang();

                jbr.setKode_jenis(kode_jenis);
                //jbr.setNama_jenis(nama_jenis);
                brg.setKode_barang(kode_barang);
                brg.setNama_barang(nama_barang);
                brg.setSatuan(satuan);
                brg.setHarga(harga);
                brg.setStok(stok);

                brg.setJns_barang(jbr);

                servis.perbaruiData(brg);
                tblModel.perbaruiData(index, brg);
                loadData();
                resetForm();
                tampilPanel();
                
            }   
        }
    }

    private void dataTabel(){
        dataBarang.setVisible(false);
        tambahBarang.setVisible(true);
        
        int row = tbl_barang.getSelectedRow();
        jLabel5.setText("Perbarui Data Barang");

        t_kodebarang.setEnabled(false);
        t_jenisbarang.setEnabled(true);
        t_namajenisbarang.setEnabled(true);

        t_kodebarang.setText        (tbl_barang.getModel().getValueAt(row, 0).toString());
        t_jenisbarang.setText       (tbl_barang.getModel().getValueAt(row, 1).toString());
        t_namajenisbarang.setText   (tbl_barang.getModel().getValueAt(row, 2).toString());
        t_namabarang.setText        (tbl_barang.getModel().getValueAt(row, 3).toString());
        cbx_satuan.setSelectedItem  (tbl_barang.getModel().getValueAt(row, 4).toString());
        t_harga.setText             (tbl_barang.getModel().getValueAt(row, 5).toString());
        t_stok.setText              (tbl_barang.getModel().getValueAt(row, 6).toString());

        aktif();
        bt_tambah.setText("PERBARUI");
        bt_batal.setVisible(true);
    }
    
    private void tampilPanel(){
        mainPanel.removeAll();
        mainPanel.add(new Master_Barang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void hapusData() {
        int index = tbl_barang.getSelectedRow();
        if (index!=-1) {
            Model_Barang brg = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(brg);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");
        
        }
    }
    
    private void simpanData(){
        if(validasiInput()==true){
            String kode_barang   = t_kodebarang.getText();
            String kode_jenis    = t_jenisbarang.getText();
            String nama_jenisbarang   = t_namajenisbarang.getText();
            String nama_barang   = t_namabarang.getText();
            String satuan        = cbx_satuan.getSelectedItem().toString();
            Long harga           = Long.parseLong(t_harga.getText());
            int stok         = Integer.parseInt(t_stok.getText());

            Model_Barang brg = new Model_Barang();
            Model_JenisBarang jbr = new Model_JenisBarang();

            brg.setKode_barang(kode_barang);
            jbr.setKode_jenis(kode_jenis);
            jbr.setNama_jenis(nama_jenisbarang);
            brg.setNama_barang(nama_barang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            brg.setStok(stok);

            brg.setJns_barang(jbr);

            servis.tambahData(brg);
            tblModel.tambahData(brg);
            loadData();
            resetForm();
            tampilPanel();
            bt_tambah.setText("TAMBAH");
        }
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if (t_kodebarang.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
        }else if (t_jenisbarang.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Kode Jenis Barang tidak boleh kosong");
        }else if (t_namajenisbarang.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Nama Jenis Barang tidak boleh kosong");
        }else if (t_namabarang.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong");
        }else if (cbx_satuan.getSelectedItem().equals(null) ){
            JOptionPane.showMessageDialog(null, "Satuan tidak boleh kosong");
        }else if (t_harga.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Harga tidak boleh kosong");
        }else if (t_stok.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong");
        }else{
            valid = true;
        }
        return valid;
    }

    
}
