/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAO_Pengguna;
import Model.Model_Pengguna;
import Service.Service_Pengguna;
import TableModel.TblMod_Pengguna;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kelompok 4
 */
public class Master_Pengguna extends javax.swing.JPanel {

    private Service_Pengguna servis = new DAO_Pengguna();
    private TblMod_Pengguna tblModel = new TblMod_Pengguna();
    
    public Master_Pengguna() {
        initComponents();
        
        tbl_pengguna.setModel(tblModel);
        tbl_pengguna.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_pengguna.getTableHeader().setOpaque(false);
        tbl_pengguna.getTableHeader().setBackground(new Color(0,48,88));
        tbl_pengguna.getTableHeader().setForeground(new Color(255,255,255));
        tbl_pengguna.setRowHeight(27);
        
        //setLocationRelativeTo(null);
        tbl_pengguna.setModel(tblModel);
        loadData();
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataPengguna = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengguna = new javax.swing.JTable();
        bt_tambahdata = new javax.swing.JPanel();
        bt_data = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_hapusdata = new javax.swing.JPanel();
        bt_hapus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_bataldata2 = new javax.swing.JPanel();
        bt_bataldata = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bt_tambahdata2 = new javax.swing.JPanel();
        bt_data1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tambahPengguna = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        t_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_password = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_telepon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_alamat = new javax.swing.JTextField();
        bt_tambahdata1 = new javax.swing.JPanel();
        bt_tambah = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bt_hapusdata1 = new javax.swing.JPanel();
        bt_batal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbx_level = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataPengguna.setBackground(new java.awt.Color(255, 255, 255));
        dataPengguna.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));

        tbl_pengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_penggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pengguna);

        bt_tambahdata.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdataMousePressed(evt);
            }
        });
        bt_tambahdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdataKeyPressed(evt);
            }
        });

        bt_data.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data.setForeground(new java.awt.Color(255, 255, 255));
        bt_data.setText("Data user");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdataLayout = new javax.swing.GroupLayout(bt_tambahdata);
        bt_tambahdata.setLayout(bt_tambahdataLayout);
        bt_tambahdataLayout.setHorizontalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_data)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        bt_tambahdataLayout.setVerticalGroup(
            bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_hapusdata.setBackground(new java.awt.Color(0, 48, 88));
        bt_hapusdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusdataMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseExited(evt);
            }
        });
        bt_hapusdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdataKeyPressed(evt);
            }
        });

        bt_hapus.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setText("HAPUS");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Delete_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_hapusdataLayout = new javax.swing.GroupLayout(bt_hapusdata);
        bt_hapusdata.setLayout(bt_hapusdataLayout);
        bt_hapusdataLayout.setHorizontalGroup(
            bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusdataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_hapus)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        bt_hapusdataLayout.setVerticalGroup(
            bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_hapusdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_bataldata2.setBackground(new java.awt.Color(0, 48, 88));
        bt_bataldata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_bataldata2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseExited(evt);
            }
        });
        bt_bataldata2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_bataldata2KeyPressed(evt);
            }
        });

        bt_bataldata.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_bataldata.setForeground(new java.awt.Color(255, 255, 255));
        bt_bataldata.setText("BATAL");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_File_Delete_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_bataldata2Layout = new javax.swing.GroupLayout(bt_bataldata2);
        bt_bataldata2.setLayout(bt_bataldata2Layout);
        bt_bataldata2Layout.setHorizontalGroup(
            bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_bataldata2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_bataldata)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        bt_bataldata2Layout.setVerticalGroup(
            bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_bataldata2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_bataldata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_bataldata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_tambahdata2.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata2MouseExited(evt);
            }
        });
        bt_tambahdata2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata2KeyPressed(evt);
            }
        });

        bt_data1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_data1.setForeground(new java.awt.Color(255, 255, 255));
        bt_data1.setText("RESET");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdata2Layout = new javax.swing.GroupLayout(bt_tambahdata2);
        bt_tambahdata2.setLayout(bt_tambahdata2Layout);
        bt_tambahdata2Layout.setHorizontalGroup(
            bt_tambahdata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_data1)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        bt_tambahdata2Layout.setVerticalGroup(
            bt_tambahdata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdata2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_data1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon_Cari2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Pengguna");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        javax.swing.GroupLayout dataPenggunaLayout = new javax.swing.GroupLayout(dataPengguna);
        dataPengguna.setLayout(dataPenggunaLayout);
        dataPenggunaLayout.setHorizontalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(dataPenggunaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dataPenggunaLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_tambahdata2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        dataPenggunaLayout.setVerticalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPenggunaLayout.createSequentialGroup()
                        .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(dataPenggunaLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        mainPanel.add(dataPengguna, "card2");

        tambahPengguna.setBackground(new java.awt.Color(255, 255, 255));
        tambahPengguna.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(0, 48, 88)));
        tambahPengguna.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("ID Pengguna");

        t_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Nama Pengguna");

        t_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });

        t_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Username");

        t_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Password");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Telepon");

        t_telepon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_teleponActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Alamat");

        t_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_alamatActionPerformed(evt);
            }
        });

        bt_tambahdata1.setBackground(new java.awt.Color(0, 48, 88));
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseExited(evt);
            }
        });
        bt_tambahdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata1KeyPressed(evt);
            }
        });

        bt_tambah.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambah.setText("TAMBAH");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Add_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_tambahdata1Layout = new javax.swing.GroupLayout(bt_tambahdata1);
        bt_tambahdata1.setLayout(bt_tambahdata1Layout);
        bt_tambahdata1Layout.setHorizontalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_tambahdata1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_tambah)
                .addGap(30, 30, 30))
        );
        bt_tambahdata1Layout.setVerticalGroup(
            bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_tambahdata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_tambahdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bt_hapusdata1.setBackground(new java.awt.Color(0, 48, 88));
        bt_hapusdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseExited(evt);
            }
        });
        bt_hapusdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdata1KeyPressed(evt);
            }
        });

        bt_batal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setText("BATAL");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Delete_File_20px.png"))); // NOI18N

        javax.swing.GroupLayout bt_hapusdata1Layout = new javax.swing.GroupLayout(bt_hapusdata1);
        bt_hapusdata1.setLayout(bt_hapusdata1Layout);
        bt_hapusdata1Layout.setHorizontalGroup(
            bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bt_hapusdata1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_batal)
                .addGap(30, 30, 30))
        );
        bt_hapusdata1Layout.setVerticalGroup(
            bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bt_hapusdata1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bt_hapusdata1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Data Pengguna");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Level");

        cbx_level.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbx_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Akses Level -", "Owner", "Staff" }));
        cbx_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_levelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahPenggunaLayout = new javax.swing.GroupLayout(tambahPengguna);
        tambahPengguna.setLayout(tambahPenggunaLayout);
        tambahPenggunaLayout.setHorizontalGroup(
            tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(tambahPenggunaLayout.createSequentialGroup()
                        .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tambahPenggunaLayout.createSequentialGroup()
                                .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(tambahPenggunaLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(tambahPenggunaLayout.createSequentialGroup()
                        .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 396, Short.MAX_VALUE))))
        );
        tambahPenggunaLayout.setVerticalGroup(
            tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_level, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahPengguna, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void tbl_penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_penggunaMouseClicked
        if(bt_data.getText().equals("TAMBAH"))
        {
            bt_data.setText("UBAH");
            
        }
        bt_hapusdata.setVisible(true);
        bt_bataldata2.setVisible(true);
        bt_tambahdata2.setVisible(true);
        bt_data1.setText("Reset Password");
    }//GEN-LAST:event_tbl_penggunaMouseClicked

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void t_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_teleponActionPerformed

    private void t_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_alamatActionPerformed

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked
//        mainPanel.removeAll();
//        mainPanel.repaint();
//        mainPanel.revalidate();
//
////        mainPanel.add(tambahPengguna);
//        mainPanel.repaint();
//        mainPanel.revalidate();
//
//        bt_tambah.setText("SIMPAN");
//
//        t_id.setText(servis.nomor());
//
//        if(bt_data.getText().equals("UBAH"))
//        {
//            dataTabel();
//        }
    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_tambahdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseEntered
//        bt_tambahdata.setBackground(new Color(1, 36, 66));
        bt_tambahdata.setBackground(new Color(1, 36, 66));
        
    }//GEN-LAST:event_bt_tambahdataMouseEntered

    private void bt_tambahdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseExited
//        bt_tambahdata.setBackground(new Color(0,48,88));
        bt_tambahdata.setBackground(new Color(124,148,7));

    }//GEN-LAST:event_bt_tambahdataMouseExited

    private void bt_tambahdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMousePressed
//        bt_tambahdata.setBackground(new Color(1, 28, 51));
        bt_tambahdata.setBackground(new Color(1, 28, 51));

    }//GEN-LAST:event_bt_tambahdataMousePressed

    private void bt_tambahdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdataKeyPressed

    }//GEN-LAST:event_bt_tambahdataKeyPressed

    private void bt_hapusdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseClicked
        hapusData();
    }//GEN-LAST:event_bt_hapusdataMouseClicked

    private void bt_hapusdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseEntered
        bt_hapusdata.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_hapusdataMouseEntered

    private void bt_hapusdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseExited
        bt_hapusdata.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_hapusdataMouseExited

    private void bt_hapusdataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMousePressed
        bt_hapusdata.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_hapusdataMousePressed

    private void bt_hapusdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdataKeyPressed

    private void bt_bataldata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseClicked
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_bataldata2MouseClicked

    private void bt_bataldata2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MouseEntered

    private void bt_bataldata2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MouseExited

    private void bt_bataldata2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2MousePressed

    private void bt_bataldata2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_bataldata2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_bataldata2KeyPressed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked
        if(bt_tambah.getText().equals("TAMBAH"))
        {
            bt_tambah.setText("SIMPAN");
            t_id.setText(servis.nomor());

        }
        else if(bt_tambah.getText().equals("SIMPAN"))
        {
            simpanData();

        }
        else if(bt_tambah.getText().equals("PERBARUI"))
        {
            perbaruiData();

        }
        else if(bt_tambah.getText().equals("RISET"))
        {
            risetpswd();

        }

    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_tambahdata1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseEntered
        bt_tambahdata1.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_tambahdata1MouseEntered

    private void bt_tambahdata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseExited
        bt_tambahdata1.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_tambahdata1MouseExited

    private void bt_tambahdata1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MousePressed
        bt_tambahdata1.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_tambahdata1MousePressed

    private void bt_tambahdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata1KeyPressed

    private void bt_hapusdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1MouseClicked

    private void bt_hapusdata1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseEntered
        bt_hapusdata1.setBackground(new Color(1, 36, 66));
    }//GEN-LAST:event_bt_hapusdata1MouseEntered

    private void bt_hapusdata1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseExited
        bt_hapusdata1.setBackground(new Color(0,48,88));
    }//GEN-LAST:event_bt_hapusdata1MouseExited

    private void bt_hapusdata1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MousePressed
        bt_hapusdata1.setBackground(new Color(1, 28, 51));
    }//GEN-LAST:event_bt_hapusdata1MousePressed

    private void bt_hapusdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdata1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdata1KeyPressed

    private void cbx_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_levelActionPerformed

    private void bt_tambahdata2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata2MousePressed

    //modive by : irwan
    private void bt_tambahdata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata2MouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahPengguna);
        mainPanel.repaint();
        mainPanel.revalidate();

//        bt_tambah.setText("SIMPAN");
        bt_tambah.setText("RISET");

        t_id.setText(servis.nomor());

        if(bt_data.getText().equals("UBAH"))
        {
            dataTabel2();
        }
        
    }//GEN-LAST:event_bt_tambahdata2MouseClicked

    private void bt_tambahdata2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata2MouseEntered

    private void bt_tambahdata2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata2MouseExited

    private void bt_tambahdata2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_batal;
    private javax.swing.JLabel bt_bataldata;
    private javax.swing.JPanel bt_bataldata2;
    private javax.swing.JLabel bt_data;
    private javax.swing.JLabel bt_data1;
    private javax.swing.JLabel bt_hapus;
    private javax.swing.JPanel bt_hapusdata;
    private javax.swing.JPanel bt_hapusdata1;
    private javax.swing.JLabel bt_tambah;
    private javax.swing.JPanel bt_tambahdata;
    private javax.swing.JPanel bt_tambahdata1;
    private javax.swing.JPanel bt_tambahdata2;
    private javax.swing.JComboBox<String> cbx_level;
    private javax.swing.JPanel dataPengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_alamat;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_password;
    private javax.swing.JTextField t_telepon;
    private javax.swing.JTextField t_username;
    private javax.swing.JPanel tambahPengguna;
    private javax.swing.JTable tbl_pengguna;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bt_hapusdata.setVisible(false);
        bt_bataldata2.setVisible(false);
        bt_tambahdata2.setVisible(false);        
        List<Model_Pengguna> list = servis.getData();
        tblModel.setData(list);
    }

    private void pencarian() {
        List<Model_Pengguna> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
    
    private void resetForm() {
        bt_tambah.requestFocus();
        t_id.setText("");
        t_nama.setText("");
    }
    
    private void nonAktif(){
        
    }

    private void perbaruiData() {
        int index = tbl_pengguna.getSelectedRow();
        if (index!=-1) {
            Model_Pengguna modis = tblModel.getData(tbl_pengguna.convertRowIndexToModel(index));
             
            if(validasiInput()==true){
            String id         = t_id.getText();
            String nama       = t_nama.getText();
            String username   = t_username.getText();
            String password   = t_password.getText();
            String telepon    = t_telepon.getText();
            String alamat     = t_alamat.getText();
            String level      = cbx_level.getSelectedItem().toString();

            Model_Pengguna pgn = new Model_Pengguna();
            pgn.setId_pengguna      (id);
            pgn.setNama_pengguna    (nama);
            pgn.setUsername         (username);
            pgn.setPassword         (password);
            pgn.setTelp_pengguna    (telepon);
            pgn.setAlamat_pengguna  (alamat);
            pgn.setLevel            (level);
                
            servis.perbaruiData(pgn);
            tblModel.perbaruiData(index, pgn);
            loadData();
            resetForm();
            
            }
        }
    }

    private void risetpswd() {
        int index = tbl_pengguna.getSelectedRow();
        if (index!=-1) {
            Model_Pengguna modis = tblModel.getData(tbl_pengguna.convertRowIndexToModel(index));
             
            if(validasiInput()==true){
            String id         = t_id.getText();
            String nama       = t_nama.getText();
            String username   = t_username.getText();
            String password   = t_password.getText();
            String telepon    = t_telepon.getText();
            String alamat     = t_alamat.getText();
            String level      = cbx_level.getSelectedItem().toString();

            Model_Pengguna pgn = new Model_Pengguna();
            pgn.setId_pengguna      (id);
            pgn.setNama_pengguna    (nama);
            pgn.setUsername         (username);
            pgn.setPassword         (password);
            pgn.setTelp_pengguna    (telepon);
            pgn.setAlamat_pengguna  (alamat);
            pgn.setLevel            (level);
                
            servis.risetpswd(pgn);
            tblModel.risetpswd(index, pgn);
            loadData();
            resetForm();
            
            }
        }
    }    
    private void hapusData() {
        int index = tbl_pengguna.getSelectedRow();
        if (index!=-1) {
            Model_Pengguna pgn = tblModel.getData(tbl_pengguna.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(pgn);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");
        
        }
    }
    
    private void dataTabel(){
        dataPengguna.setVisible(false);
        tambahPengguna.setVisible(true);
        
        int row = tbl_pengguna.getSelectedRow();

        t_nama.setEnabled(true);
        t_id.setEnabled(false);

        t_id.setText        (tbl_pengguna.getModel().getValueAt(row, 0).toString());
        t_nama.setText      (tbl_pengguna.getModel().getValueAt(row, 1).toString());
        t_username.setText  (tbl_pengguna.getModel().getValueAt(row, 2).toString());
        t_password.setText  (tbl_pengguna.getModel().getValueAt(row, 3).toString());
        t_telepon.setText   (tbl_pengguna.getModel().getValueAt(row, 3).toString());
        t_alamat.setText    (tbl_pengguna.getModel().getValueAt(row, 4).toString());
        cbx_level.setSelectedItem(tbl_pengguna.getModel().getValueAt(row, 5).toString());

        jLabel9.setVisible(false);
//        jLabel9.setVisible(true);
        t_password.setVisible(false);
//        t_password.setVisible(true);        
        bt_tambah.setText("PERBARUI");
        bt_batal.setVisible(true);
        jLabel5.setText("Perbaharui Data");
    }

    private void dataTabel2(){
        dataPengguna.setVisible(false);
        tambahPengguna.setVisible(true);
        
        int row = tbl_pengguna.getSelectedRow();

//        t_nama.setEnabled(true);
        t_nama.setEnabled(false);
        t_id.setEnabled(false);
        t_username.setEnabled(false);

        t_id.setText        (tbl_pengguna.getModel().getValueAt(row, 0).toString());
        t_nama.setText      (tbl_pengguna.getModel().getValueAt(row, 1).toString());
        t_username.setText  (tbl_pengguna.getModel().getValueAt(row, 2).toString());
        t_password.setText  (tbl_pengguna.getModel().getValueAt(row, 6).toString());
        t_telepon.setText   (tbl_pengguna.getModel().getValueAt(row, 6).toString());
        t_alamat.setText    (tbl_pengguna.getModel().getValueAt(row, 6).toString());
        cbx_level.setSelectedItem(tbl_pengguna.getModel().getValueAt(row, 5).toString());

//        jLabel9.setVisible(false);
        jLabel9.setVisible(true);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
                                
//        t_password.setVisible(false);
        t_telepon.setVisible(false);        
        t_alamat.setVisible(false);        
        cbx_level.setVisible(false);        

        t_password.setVisible(true);        
        bt_tambah.setText("RISET");
        bt_batal.setVisible(true);
        jLabel5.setText("Riset Pswd Data");
    }
    
    private void tampilPanel(){
        mainPanel.removeAll();
        mainPanel.add(new Master_Pengguna());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void simpanData() {
        if(validasiInput()==true){
            String id         = t_id.getText();
            String nama       = t_nama.getText();
            String username   = t_username.getText();
            String password   = t_password.getText();
            String telepon    = t_telepon.getText();
            String alamat     = t_alamat.getText();
            String level     = cbx_level.getSelectedItem().toString();

            Model_Pengguna pgn = new Model_Pengguna();
            pgn.setId_pengguna      (id);
            pgn.setNama_pengguna    (nama);
            pgn.setUsername         (username);
            pgn.setPassword         (password);
            pgn.setTelp_pengguna    (telepon);
            pgn.setAlamat_pengguna  (alamat);
            pgn.setLevel            (level);

            servis.tambahData(pgn);
            tblModel.tambahData(pgn);
            tampilPanel();
            loadData();
            resetForm();
            bt_tambah.setText("TAMBAH");
        }
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if (t_id.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "ID Pengguna tidak boleh kosong");
        }else if (t_nama.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Nama Pengguna tidak boleh kosong");
        }else if (t_username.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        }else if (t_password.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        }else if (t_telepon.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Telepon tidak boleh kosong");
        }else if (t_alamat.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong");
        }else if(cbx_level.getSelectedItem().equals("- Pilih Akses Level -")){
            JOptionPane.showMessageDialog(null, "Level tidak boleh kosong");
        }else{
            valid = true;
        }
        return valid;
    }
}
